import { Copy, SiteLink } from '@/components/site-context';
import { CaseShell } from '@/components/case-shell';
import { ProjectIntro } from '@/components/project-intro';
import { CultureExplorer } from '@/components/culture-explorer';
import products from '@/lib/culture-competitors.json';
import { t } from '@/lib/bilingual';
export const metadata = { title: '3D cell culture | Bill Huang', description: 'Technical and commercial due diligence: seven 3D culture competitors, product specifications, catalogue prices and adoption economics.', alternates: { canonical: 'https://betoadfish.github.io/intelligence/3d-cell-culture', languages: { en: 'https://betoadfish.github.io/intelligence/3d-cell-culture', 'zh-CN': 'https://betoadfish.github.io/zh/intelligence/3d-cell-culture' } } };
export default function Culture() {
 return <CaseShell theme="culture" category="Biotech intelligence" title={t('3D cell culture','3D 细胞培养')} subtitle={t('From scaffold chemistry to a defensible investment case.','从支架材料的技术特点，判断商业化价值。')} role={t('Investment analyst intern','投资分析实习生')} date={t('March 2024','2024 年 3 月')} institution={t('Shanghai Dynamax Group · Private equity','上海冠亚投资 · 私募股权投资')} summary={t('I assessed a scaffold-based 3D cell culture business during my internship at Shanghai Dynamax Group. I compared seven competing platforms and translated material properties into questions about biological validation, customer adoption and the economics of a laboratory workflow.','在上海冠亚投资实习期间，我评估了一家基于支架材料的 3D 细胞培养企业。我比较了七种竞品，将材料参数逐项转化为生物学验证、客户采用和实验工作流成本方面的尽调问题。')}>
 <ProjectIntro title={t('What makes a better cell model a product customers will buy?', '更好的细胞模型，怎样成为客户愿意购买的产品？')} lead={t('Three-dimensional culture gives cells a spatial environment that a flat surface cannot provide. Scaffolds can support that environment, but a commercial platform must also fit how researchers seed cells, run experiments and obtain usable results.','三维培养为细胞提供平面培养难以呈现的空间环境。支架材料可以支持这一环境，但要成为商业产品，还必须适应研究者接种细胞、开展实验和获取可用结果的完整流程。')} items={[
 {title:t('The technology','技术是什么'),body:t('A scaffold combines physical support with a particular chemical environment. Stiffness, porosity, adhesion and degradation can affect how the culture is established and measured.','支架同时提供物理支撑和特定化学环境。刚度、孔隙、黏附和降解特性，会影响培养体系如何建立，以及后续怎样测量。')},
 {title:t('The customer','谁会购买'),body:t('Academic groups, organoid developers, CROs and pharmaceutical screening teams have different requirements. The addressable opportunity starts with a specific workflow and buying decision.','高校课题组、类器官开发团队、CRO 和药企筛选部门的需求并不相同。判断可服务市场，应先明确具体工作流及其采购决策。')},
 {title:t('The adoption problem','采用新产品的阻力'),body:t('A new material competes with an established protocol as well as with another supplier. Revalidation, staff time and compatibility with historical data can outweigh a lower catalogue price.','新材料既与其他供应商竞争，也与客户已经建立的实验流程竞争。重新验证、人员时间和历史数据可比性的成本，可能超过目录价上的节省。')},
 {title:t('My diligence question','我如何提出尽调问题'),body:t('Could controllable material chemistry deliver reproducible biological results, within a workflow customers would adopt and repeat? I used that question to connect the technical comparison to the investment assessment.','可控的材料化学，能否在客户愿意采用并持续使用的流程中，产生可重复的生物学结果？我以此将技术比较与投资评估联系起来。')}
 ]}/>
 <section className="editorial-section editorial-grid"><div><p className="eyebrow"><Copy>{t('01 / Investment thesis','01 / 投资逻辑')}</Copy></p><h2><Copy>{t('Start with a beachhead application.','先找到可以切入的具体应用。')}</Copy></h2></div><div><p><Copy>{t('A claim of broad 3D-culture applicability is difficult to underwrite without evidence from a defined cell model. My review separated adjustable material properties from demonstrated cell survival, function and reproducibility. The assessed business still needed stronger validation across cell types and more complex models.','如果没有明确细胞模型中的证据，“广泛适用于 3D 培养”很难成为扎实的投资依据。我将材料参数可调与细胞存活、功能和重复性是否得到验证分开检查。被评估企业仍需补强不同细胞类型及复杂模型中的生物学验证。')}</Copy></p><p><Copy>{t('The commercial implication is to define an initial customer profile and a narrow use case, then ask which result would justify switching. This is the investment framework developed from the review, not a claim that customer conversion or financial returns were measured.','商业上的落点是先明确初始客户画像（ICP）和具体应用，再判断什么结果足以促使客户切换。这是由技术评估延伸出的投资分析框架，项目并未实测客户转化或财务回报。')}</Copy></p></div></section>
 <section className="editorial-section"><p className="eyebrow"><Copy>{t('02 / Competitive landscape','02 / 竞争格局')}</Copy></p><h2><Copy>{t('Seven platforms, with different units of value.','七种平台，价值与成本的比较口径各不相同。')}</Copy></h2><p><Copy>{t('The original 2024 review compared these seven platforms. The catalogue references below were refreshed on 6 September 2026; the selected SKUs illustrate each platform and are not presented as the exact products or prices available during the internship. Currencies and package units are retained, with no assumed discounts, freight or currency conversion.','2024 年原报告比较了这七种平台。下表目录资料更新于 2026 年 9 月 6 日，所选 SKU 用于具体展示各平台，不代表实习时使用的是相同型号或价格。表中保留币种和包装单位，不假设折扣、运费或汇率换算。')}</Copy></p>
 <div className="comparison-scroll"><table className="comparison-table competitors"><thead><tr>{[t('Platform / source','平台 / 来源'),t('Material and specification','材料与规格'),t('Listed price / basis','目录价格 / 口径'),t('Diligence implication','尽调关注点')].map((x,i)=><th key={i}><Copy>{x}</Copy></th>)}</tr></thead><tbody>{products.map(product=><tr key={product.name}><td><SiteLink href={product.url} target="_blank" rel="noreferrer">{product.name} ↗</SiteLink></td><td><Copy>{product.material}</Copy><br/><span className="small muted"><Copy>{product.spec}</Copy></span></td><td><Copy>{product.price}</Copy></td><td><Copy>{product.implication}</Copy></td></tr>)}</tbody></table></div></section>
 <section className="editorial-section"><p className="eyebrow"><Copy>{t('03 / Unit economics','03 / 单位经济性')}</Copy></p><h2><Copy>{t('Compare the cost of a usable result.','比较获得一次有效结果的成本。')}</Copy></h2><p><Copy>{t('Price per mL is only useful within a comparable formulation. Matrigel 356234 lists at USD 39.01 per mL of supplied matrix; ToGro G94-1 works out at EUR 122.08 per mL of final gel; Alvetex AVP005-96 is approximately JPY 795.83 per insert. These are arithmetic unit conversions, not a ranking of value or equivalent performance.','只有在配方可比时，每毫升价格才有意义。Matrigel 356234 折合每毫升供货基质 39.01 美元；ToGro G94-1 折合每毫升最终凝胶 122.08 欧元；Alvetex AVP005-96 则约为每个 insert 795.83 日元。这些只是单位换算，不是性价比排序，也不代表性能等效。')}</Copy></p>
 <div className="result-banner"><p className="eyebrow"><Copy>{t('A workflow-level denominator','以完整工作流为口径')}</Copy></p><h3><Copy>{t('Cost per valid well = total workflow cost ÷ wells that meet the assay criteria','每个有效孔的成本 = 工作流总成本 ÷ 达到实验判定标准的孔数')}</Copy></h3><p><Copy>{t('Include matrix, supplements, plates, recovery reagents, labour, equipment use and repeat experiments. A premium-priced material could be economical if it reduces failures or hands-on time; that proposition needs measured customer-workflow data.','总成本应包括基质、添加物、培养板、回收试剂、人工、设备使用和重做实验。单价较高的材料如果能减少失败或操作时间，也可能更经济；但这一价值主张需要客户工作流中的实测数据。')}</Copy></p></div></section>
 <section className="editorial-section"><p className="eyebrow"><Copy>{t('04 / Commercial diligence','04 / 商业尽调')}</Copy></p><h2><Copy>{t('Translate technical advantages into testable business questions.','把技术优势转化为可验证的商业问题。')}</Copy></h2><div className="intro-grid">{[
 [t('Adoption and switching cost','客户采用与切换成本'),t('Which protocol is replaced, who signs off the validation, and how long does a pilot take? Request pilot completion, repeat-order and protocol-transfer evidence by customer segment.','替换哪一套流程？谁负责验证通过？试用需要多久？应按客户群检查试用完成、复购和流程迁移记录。')],
 [t('Recurring revenue and retention','持续收入与留存'),t('A consumable can generate recurring revenue when embedded in a repeated assay. Test cohort reorder behaviour and consumption per active workflow, rather than treating one-off research purchases as recurring demand.','耗材进入持续运行的实验流程后，才可能形成稳定复购。应看客户分组后的再次采购和活跃流程用量，不能把一次性科研采购当作持续需求。')],
 [t('Gross margin and scale-up','毛利与规模化'),t('Ask for batch yields, release-testing cost, scrap, shelf life, distribution margin and technical-support burden. A high selling price alone does not establish attractive gross margin.','需要核查批次产出、放行检测成本、报废、保质期、渠道分成和技术支持投入。售价高，本身不能证明毛利水平有吸引力。')],
 [t('Defensibility and supply','竞争壁垒与供应'),t('Assess formulation IP, application data, validated protocols and dependable supply together. Distinguish research-use sales from the additional qualification needed for clinical or manufacturing applications.','综合评估配方知识产权、应用数据、已验证流程和可靠供货。研究用途销售与临床、生产相关用途所需的额外资质和验证，也应分别评估。')]
 ].map(([title,body],i)=><article key={i}><h3><Copy>{title}</Copy></h3><p><Copy>{body}</Copy></p></article>)}</div></section>
 <CultureExplorer/>
 <section className="editorial-section editorial-grid"><div><p className="eyebrow"><Copy>{t('My contribution and finding','我的工作与主要判断')}</Copy></p><h2><Copy>{t('Make the validation gap actionable.','把验证缺口转化为下一步尽调要求。')}</Copy></h2></div><div><p><Copy>{t('I produced an overview of 3D-culture methods and a seven-platform comparison using scientific literature, product documentation and market material. The review put biological function, reproducibility, preparation, cell recovery and cost into one assessment.','我依据科学文献、产品资料和市场材料，完成了 3D 培养方法综述及七种平台的竞品比较，将生物学功能、重复性、制备、细胞回收和成本纳入同一份评估。')}</Copy></p><p><Copy>{t('The central finding was that tunable material chemistry needed stronger model-specific biological evidence before it could support broad product claims. I translated this into focused evidence requests for the investment team. Investment decisions remained with the team; this public case does not claim a deal outcome.','主要判断是：材料化学可调，还不足以支持广泛的产品应用主张，需要更充分的特定模型生物学证据。我据此为投资团队提出有针对性的补充资料要求。投资决策由团队负责，本案例不据此声称具体交易结果。')}</Copy></p></div></section>
 <details className="source-disclosure"><summary><Copy>{t('Sources and dating','资料来源与时间口径')}</Copy></summary><p><Copy>{t('The 2024 account follows two original project reports and the personal CV and research account. The product table is a separately dated 2026 update based on the linked supplier catalogues and UPM’s 2025 annual report. Listed prices are observations, not purchase quotations; unpublished prices remain unquoted. I did not run a laboratory benchmark or audit the companies’ financial statements.','2024 年工作依据两份原始项目报告、个人简历和项目记录。竞品表是单独标注时间的 2026 年更新，依据表内链接的供应商目录及 UPM 2025 年年报。所列价格是查询记录，并非采购报价；未核实的价格不填估计值。我没有进行产品实验室横向测评，也未审计这些企业的财务报表。')}</Copy></p></details>
 </CaseShell>;
}
