import { Copy, SiteLink } from '@/components/site-context';
import { CaseShell } from '@/components/case-shell';
import { ProjectIntro } from '@/components/project-intro';
import { CultureJourney } from '@/components/case-journeys';
import { t } from '@/lib/bilingual';
export const metadata = { title: '3D cell culture | Bill Huang', description: 'Technical and commercial due diligence: seven 3D culture competitors, product specifications, catalogue prices and adoption economics.', alternates: { canonical: 'https://betoadfish.github.io/intelligence/3d-cell-culture', languages: { en: 'https://betoadfish.github.io/intelligence/3d-cell-culture', 'zh-CN': 'https://betoadfish.github.io/zh/intelligence/3d-cell-culture' } } };
export default function Culture() {
 return <CaseShell theme="culture" category="Biotech intelligence" title={t('3D cell culture','3D 细胞培养')} subtitle={t('From scaffold chemistry to a defensible investment case.','从支架材料的技术特点，判断商业化价值。')} role={t('Investment analyst intern','投资分析实习生')} date={t('March 2024','2024 年 3 月')} institution={t('Shanghai Dynamax Group · Private equity','上海冠亚投资 · 私募股权投资')} summary={t('I assessed a scaffold-based 3D cell culture business during my internship at Shanghai Dynamax Group. I compared seven competing platforms and translated material properties into questions about biological validation, customer adoption and the economics of a laboratory workflow.','在上海冠亚投资实习期间，我评估了一家基于支架材料的 3D 细胞培养企业。我比较了七种竞品，将材料参数逐项转化为生物学验证、客户采用和实验工作流成本方面的尽调问题。')}>
 <ProjectIntro title={t('What makes a better cell model a product customers will buy?', '更好的细胞模型，怎样成为客户愿意购买的产品？')} lead={t('Three-dimensional culture gives cells a spatial environment that a flat surface cannot provide. Scaffolds can support that environment, but a commercial platform must also fit how researchers seed cells, run experiments and obtain usable results.','三维培养为细胞提供平面培养难以呈现的空间环境。支架材料可以支持这一环境，但要成为商业产品，还必须适应研究者接种细胞、开展实验和获取可用结果的完整流程。')} items={[
 {title:t('The technology','技术是什么'),body:t('A scaffold combines physical support with a particular chemical environment. Stiffness, porosity, adhesion and degradation can affect how the culture is established and measured.','支架同时提供物理支撑和特定化学环境。刚度、孔隙、黏附和降解特性，会影响培养体系如何建立，以及后续怎样测量。')},
 {title:t('The customer','谁会购买'),body:t('Academic groups, organoid developers, CROs and pharmaceutical screening teams have different requirements. The addressable opportunity starts with a specific workflow and buying decision.','高校课题组、类器官开发团队、CRO 和药企筛选部门的需求并不相同。判断可服务市场，应先明确具体工作流及其采购决策。')},
 {title:t('The adoption problem','采用新产品的阻力'),body:t('A new material competes with an established protocol as well as with another supplier. Revalidation, staff time and compatibility with historical data can outweigh a lower catalogue price.','新材料既与其他供应商竞争，也与客户已经建立的实验流程竞争。重新验证、人员时间和历史数据可比性的成本，可能超过目录价上的节省。')},
 {title:t('My diligence question','我如何提出尽调问题'),body:t('Could controllable material chemistry deliver reproducible biological results, within a workflow customers would adopt and repeat? I used that question to connect the technical comparison to the investment assessment.','可控的材料化学，能否在客户愿意采用并持续使用的流程中，产生可重复的生物学结果？我以此将技术比较与投资评估联系起来。')}
 ]}/>
 <CultureJourney/>
 <section className="editorial-section editorial-grid"><div><p className="eyebrow"><Copy>{t('My contribution and finding','我的工作与主要判断')}</Copy></p><h2><Copy>{t('Make the validation gap actionable.','把验证缺口转化为下一步尽调要求。')}</Copy></h2></div><div><p><Copy>{t('I produced an overview of 3D-culture methods and a seven-platform comparison using scientific literature, product documentation and market material. The review put biological function, reproducibility, preparation, cell recovery and cost into one assessment.','我依据科学文献、产品资料和市场材料，完成了 3D 培养方法综述及七种平台的竞品比较，将生物学功能、重复性、制备、细胞回收和成本纳入同一份评估。')}</Copy></p><p><Copy>{t('The central finding was that tunable material chemistry needed stronger model-specific biological evidence before it could support broad product claims. I translated this into focused evidence requests for the investment team.','主要判断是：材料化学可调，还不足以支持广泛的产品应用主张，需要更充分的特定模型生物学证据。我据此为投资团队提出有针对性的补充资料要求。')}</Copy></p></div></section>

 </CaseShell>;
}
