import { Copy } from '@/components/site-context';
import { CaseShell } from '@/components/case-shell';
import { ProjectIntro } from '@/components/project-intro';
import { YiduJourney } from '@/components/yidu-journey';
import { t } from '@/lib/bilingual';
export const metadata={title:'Yidu healthcare research | Bill Huang',description:'Organising clinician interviews into patient profiles, decision pathways, evidence questions and follow-up needs.',alternates:{canonical:'https://betoadfish.github.io/intelligence/yidu',languages:{en:'https://betoadfish.github.io/intelligence/yidu','zh-CN':'https://betoadfish.github.io/zh/intelligence/yidu'}}};
export default function Yidu(){return <CaseShell theme="yidu" category="Biotech intelligence" title={t('Healthcare research','医药研究与分析')} subtitle={t('Understanding the decisions behind a treatment pathway.','理解诊疗路径背后的判断。')} role={t('Research synthesis & analysis','研究整理与分析')} date="2026" institution={t('Yidu','医渡科技')} summary={t('At Yidu, I worked with clinician interview material in a stroke care research project. My work connected patient profiles, decision pathways, evidence questions and follow-up needs, turning detailed source material into a structure the project team could discuss and develop.','在医渡科技的卒中诊疗研究项目中，我参与整理医生访谈，将患者画像、决策路径、证据问题和随访需求联系起来，把细节繁多的材料整理为便于项目团队讨论和推进的分析结构。')}>
<ProjectIntro title={t('What connects clinical evidence to everyday practice?','临床证据如何与日常诊疗联系起来？')} lead={t('The project examined how clinicians described patient needs and decisions across stroke care. Understanding those decisions required attention to the evidence, the patient context and the practical arrangements around ongoing care.','项目关注医生如何描述卒中患者的需求，以及诊疗过程中如何作出判断。理解这些判断，需要同时看证据、患者所处的情境，以及持续管理所依赖的实际安排。')} items={[
{title:t('The research setting','研究背景'),body:t('Clinician interviews provided accounts of current practice, concerns and unmet needs. These accounts supplied context for analysis, rather than a controlled comparison of treatments.','医生访谈提供了当前做法、实际顾虑和未满足需求的线索。这些描述为分析补充背景，其本身并非治疗效果的对照研究。')},
{title:t('The analytical challenge','分析难点'),body:t('One interview could move between patient characteristics, personal experience and recommendations. I needed to organise those layers without turning a reported impression into an established finding.','一次访谈可能同时涉及患者特征、个人经验和改进建议。整理时需要区分这些层次，避免把受访者的感受写成已经证实的结论。')},
{title:t('The project outputs','项目产出'),body:t('Patient profiles, pathway diagrams, FAQ material and follow-up analyses made different parts of the research easier to review together.','患者画像、路径图、FAQ 材料和随访分析，让研究中的不同问题可以放在一起审阅和讨论。')},
{title:t('My focus','我的工作重点'),body:t('I focused on structuring the material and explaining how an observation led to a question, an interpretation or a proposed next step.','我的工作重点是组织材料，并说明一项观察怎样引出问题、形成解读，或转化为下一步建议。')}
]}/><YiduJourney/>
<section className="editorial-section editorial-grid"><div><p className="eyebrow"><Copy>{t('What this work developed','这段经历带来的能力')}</Copy></p><h2><Copy>{t('Keep the reasoning visible.','让分析的依据看得见。')}</Copy></h2></div><div><p><Copy>{t('This work strengthened how I organise qualitative evidence. A clear pathway makes it easier to identify what is supported, where views differ and which questions need additional research before a recommendation can be made.','这段经历锻炼了我组织定性证据的能力。清楚的分析路径，能帮助团队看出哪些判断有依据、哪些地方存在分歧，以及提出建议前还需要研究什么。')}</Copy></p><p className="small muted"><Copy>{t('This case presents the analytical approach at project level. Interview quotations, individual records and client-specific recommendations are omitted. The diagrams describe research structure and are not clinical guidance.','本案例展示项目层面的分析方法，省略访谈原话、个体记录和客户具体建议。图示用于说明研究结构，不构成诊疗指导。')}</Copy></p></div></section></CaseShell>;}
