import { Copy } from '@/components/site-context';
import { CaseShell } from '@/components/case-shell';
import { ProjectIntro } from '@/components/project-intro';
import { SlideWorkbench } from '@/components/slide-workbench';
import { YiduJourney } from '@/components/yidu-journey';
import { t } from '@/lib/bilingual';
export const metadata={title:'Yidu healthcare research | Bill Huang',description:'Organising clinician interviews into patient profiles, decision pathways, evidence questions and follow-up needs.',alternates:{canonical:'https://betoadfish.github.io/intelligence/yidu',languages:{en:'https://betoadfish.github.io/intelligence/yidu','zh-CN':'https://betoadfish.github.io/zh/intelligence/yidu'}}};
export default function Yidu(){return <CaseShell theme="yidu" category="Biotech intelligence" title={t('Healthcare research','医药研究与分析')} subtitle={t('Clinician interviews and evidence review in stroke prevention.','卒中预防相关的医生访谈与证据整理。')} role={t('Consulting Intern','咨询实习生')} date={t('2026 · Aug–Sep','2026 年 8–9 月')} institution={t('Yidu','医渡科技')} summary={t('At Yidu, I organised clinician interviews and research material on secondary prevention after ischaemic stroke, including questions about factor XI (FXI/FXIa). I used this material to prepare patient profiles, pathway diagrams and evidence FAQs.','在医渡科技，我整理了缺血性卒中二级预防相关的医生访谈和研究材料，其中包括凝血因子 XI（FXI/FXIa）的研究问题。具体工作包括患者画像、诊疗路径图和证据问答材料。')}>
<ProjectIntro title={t('What connects clinical evidence to everyday practice?','临床证据如何与日常诊疗联系起来？')} lead={t('The project examined how clinicians described patient needs and decisions across stroke care. The therapeutic context was secondary prevention after ischaemic stroke: how clinicians weigh recurrent ischaemic events, bleeding concerns and the evidence for emerging antithrombotic approaches, then connect those questions to patient selection and follow-up.','项目关注医生如何描述卒中患者的需求，以及诊疗过程中如何作出判断。治疗背景是缺血性卒中后的二级预防：医生如何权衡缺血事件复发、出血顾虑与新型抗栓方案的证据，再将这些问题落实到患者选择和随访管理。')} items={[
{title:t('The research setting','研究背景'),body:t('Clinician interviews provided accounts of current practice, concerns and unmet needs. These accounts supplied context for analysis, rather than a controlled comparison of treatments.','医生访谈提供了当前做法、实际顾虑和未满足需求的线索。这些描述为分析补充背景，其本身并非治疗效果的对照研究。')},
{title:t('The analytical challenge','分析难点'),body:t('One interview could move between patient characteristics, personal experience and recommendations. I needed to organise those layers without turning a reported impression into an established finding.','一次访谈可能同时涉及患者特征、个人经验和改进建议。整理时需要区分这些层次，避免把受访者的感受写成已经证实的结论。')},
{title:t('The project outputs','项目产出'),body:t('Patient profiles, pathway diagrams, FAQ material and follow-up analyses made different parts of the research easier to review together.','患者画像、路径图、FAQ 材料和随访分析，让研究中的不同问题可以放在一起审阅和讨论。')},
{title:t('My focus','我的工作重点'),body:t('I focused on structuring the material and explaining how an observation led to a question, an interpretation or a proposed next step.','我的工作重点是组织材料，并说明一项观察怎样引出问题、形成解读，或转化为下一步建议。')}
]}/><SlideWorkbench/><YiduJourney/>
<section className="editorial-section ai-practice"><p className="eyebrow"><Copy>{t("AI-assisted research and communication","AI 辅助研究与表达")}</Copy></p><h2><Copy>{t("Tools I use","我使用的工具")}</Copy></h2><p><Copy>{t("I use AI to organise sources, outline presentations and review drafts. For larger tasks I divide the work between agents, specify their source material and instructions, then check the combined output against the originals. I make the final decisions about evidence and wording.","我用 AI 整理资料、拟演示文稿提纲和检查初稿。任务较大时，会拆分给不同 agent，明确参考材料和要求，再对照原文核查合并后的结果。证据取舍和最终措辞由我判断。")}</Copy></p><div className="ai-task-grid">{[t("Source organisation","资料整理"),t("Narrative and slide design","论证与页面设计"),t("Independent review","独立审阅")].map((v,i)=><div key={i}><strong><Copy>{v}</Copy></strong></div>)}</div></section><section className="editorial-section editorial-grid"><div><p className="eyebrow"><Copy>{t('What this work developed','这段经历带来的能力')}</Copy></p><h2><Copy>{t('What I learned.','这段工作教会我的事。')}</Copy></h2></div><div><p><Copy>{t('I learned to separate interview observations, published findings and my own interpretation. That distinction helps a team see where clinicians disagree and which questions need more research.','这段工作让我更注意区分访谈观察、已发表的研究结果和自己的解读。这样整理后，团队更容易看清医生的分歧，以及哪些问题还需要补充研究。')}</Copy></p><p className="small muted"><Copy>{t('This case presents the analytical approach at project level. Interview quotations, individual records and client-specific recommendations are omitted. The diagrams describe research structure and are not clinical guidance.','本案例展示项目层面的分析方法，省略访谈原话、个体记录和客户具体建议。图示用于说明研究结构，不构成诊疗指导。')}</Copy></p></div></section></CaseShell>;}
