'use client';
import { ProjectJourney, JourneyFlow, type JourneyStep } from './project-journey';
import { lazy, Suspense } from 'react';
const PetExplorer=lazy(()=>import('./pet-explorer').then(m=>({default:m.PetExplorer})));
const McrExplorer=lazy(()=>import('./mcr-explorer').then(m=>({default:m.McrExplorer})));
import { CultureComparison } from './culture-comparison';
import { Copy } from './site-context';
import { t } from '@/lib/bilingual';

const petSteps:JourneyStep[]=[
 {id:'expression',label:t('Expression','表达条件'),title:t('Find a route to soluble protein.','先找到可用的表达条件。'),method:t('I compared constructs, bacterial strains and IPTG induction conditions at small scale, then checked the samples by SDS-PAGE before scaling up.','我在小规模培养中比较构建体、菌株和 IPTG 诱导条件，用 SDS-PAGE 检查样品后，再选择扩大培养的条件。'),result:t('The small-scale screen helped distinguish low expression from possible solubility problems.','小规模筛选帮助我区分表达不足与可能的可溶性问题。'),next:t('Follow the selected preparations through purification.','接着跟踪选定样品在纯化过程中的回收。')},
 {id:'purification',label:t('Purification','蛋白纯化'),title:t('Track where useful protein is recovered.','跟踪蛋白在哪一步被回收。'),method:t('I used His-tag affinity purification and size-exclusion chromatography to prepare CCH11 and TurboPETase for characterisation.','我使用 His 标签亲和纯化和体积排阻色谱，制备适合表征的 CCH11 与 TurboPETase。'),result:t('CCH11 recovery improved; TurboPETase remained difficult to recover, with solubility a suspected cause.','CCH11 的回收得到改善；TurboPETase 仍较难获得，可溶性是重点考虑的原因之一。'),next:t('Revisit the host and tag where recovery remains difficult.','对于回收仍困难的蛋白，继续考虑宿主和标签。')},
 {id:'host',label:t('Host & tag','宿主与标签'),title:t('Reconsider how the protein is made.','从表达体系寻找新的可能。'),method:t('I explored tag changes and a move from bacterial to yeast expression, followed by calorimetry.','我尝试调整标签、从细菌转向酵母表达，并开展后续量热分析。'),result:t('Changing host and tag creates new production options, while folding and modification remain mechanisms to test.','宿主与标签调整提供了新的制备条件；折叠和修饰仍需通过实验分别检验。'),next:t('Interpret the activity together with the preparation history.','将活性读数与蛋白的制备过程一起解释。')},
 {id:'characterisation',label:t('Activity readout','活性表征'),title:t('Connect an assay signal to the preparation.','把检测信号与蛋白样品联系起来。'),method:t('I worked with plate-reader and HPLC characterisation. The CCH11 traces compare test wells with controls for two substrate conditions.','我参与酶标仪与 HPLC 表征。CCH11 曲线比较了两种底物条件下实验孔和对照孔的响应。'),result:t('Test wells show a larger A550 decrease than controls. Quantitative enzyme comparisons also need matched inputs and product calibration.','实验孔的 A550 下降幅度大于对照孔；定量比较酶性能，还需匹配蛋白用量并校准产物。'),next:t('Use matched functional-protein inputs before attributing a difference to catalysis.','先匹配功能蛋白用量，再判断差异是否来自催化本身。')},
];
export function PetJourney(){return <ProjectJourney steps={petSteps} title={t('From expression to an activity readout.','从表达条件，走到活性读数。')} visuals={[
 <JourneyFlow key="expression" kicker={t('Small-scale screening','小规模筛选')} nodes={[[t('Construct','构建体'),t('Protein sequence and tag','序列与标签')],[t('Culture','培养'),t('Strain and induction','菌株与诱导')],['SDS-PAGE',t('Inspect the preparation','检查样品')]]}/>,
 <JourneyFlow key="purification" kicker={t('Protein recovery','蛋白回收')} nodes={[[t('His tag','His 标签'),t('Affinity purification','亲和纯化')],['SEC',t('Separate by size','按大小分离')],[t('Sample','样品'),t('Check recovery','检查回收')]]} note={t('CCH11 recovery improved; TurboPETase prompted further optimisation.','CCH11 回收改善，TurboPETase 则推动了进一步优化。')}/>,
 <JourneyFlow key="host" kicker={t('A change in production conditions','改变制备条件')} nodes={[[t('Tag','标签'),t('Change the construct','调整构建体')],[t('Yeast','酵母'),t('Explore another host','尝试另一宿主')],[t('Calorimetry','量热'),t('Characterise the sample','表征样品')]]}/>,
 <JourneyFlow key="activity" kicker={t('A meaningful comparison','可解释的比较')} nodes={[[t('Test','实验孔'),t('Enzyme and substrate','酶与底物')],[t('Control','对照孔'),t('Resolve background','识别背景')],[t('Difference','响应差异'),t('Check input and calibration','检查用量与校准')]]}/>,
 ]} evidence={[null,null,null,<Suspense key="traces" fallback={<p role="status"><Copy>{t('Loading assay curves…','正在加载实验曲线…')}</Copy></p>}><PetExplorer/></Suspense>]} evidenceLabels={[null,null,null,t('Explore assay curves','查看实验曲线')]}/>;}

const mcrSteps:JourneyStep[]=[
 {id:'screening',label:t('Combination screen','联用筛选'),title:t('Map growth across concentration pairs.','从浓度组合中寻找生长变化。'),method:t('I ran MIC and checkerboard experiments with colistin and natural compounds, then analysed the growth readouts.','我开展黏菌素与天然化合物的 MIC、棋盘法实验，并分析生长读数。'),result:t('The screen identified concentration patterns worth following up in mechanistic experiments.','筛选得到值得继续追问机制的浓度组合与响应变化。'),next:t('Ask whether the combination response involves changes to the membrane.','进一步考察联合用药响应是否涉及细胞膜变化。')},
 {id:'membrane',label:t('Membrane assays','膜相关检测'),title:t('Make the fluorescence readout interpretable.','先让荧光读数能够被解释。'),method:t('I refined PI and NPN measurements by checking reagent freshness, concentration, spectral overlap, growth phase and OD normalisation.','我通过检查试剂新鲜度、浓度、光谱重叠、生长阶段与 OD 归一化，调整 PI 和 NPN 测量。'),result:t('Assay development identified controls needed to separate membrane changes from measurement effects.','检测优化明确了区分膜变化与测量条件影响所需的对照。'),next:t('Use those controls to test the membrane explanation.','在对照齐备后，检验膜相关解释。')},
 {id:'mechanism',label:t('Next experiment','机制检验'),title:t('Move from a growth phenotype to a causal test.','从生长表型走向机制检验。'),method:t('I connected the initial growth screen to membrane-permeability experiments, checking the measurement before assigning a cause.','我把初步生长筛选与膜通透性实验连接起来，在归因之前先检查测量本身。'),result:t('The project established a screening and assay-development workflow. The molecular explanation remains a question for targeted experiments.','项目建立了筛选与检测优化流程；分子层面的解释仍需要针对性实验。'),next:t('Test reproducibility, membrane effects and dependence on MCR-1 separately.','分别检验重复性、膜效应，以及响应是否依赖 MCR-1。')},
];
export function McrJourney(){return <ProjectJourney steps={mcrSteps} title={t('Screen the response. Test the mechanism.','先筛选响应，再检验机制。')} visuals={[
 <JourneyFlow key="screen" kicker={t('Two concentration axes','两个浓度维度')} nodes={[[t('Colistin','黏菌素'),t('Vary the concentration','改变浓度')],[t('Adjuvant','候选增效剂'),t('Combine concentrations','组合浓度')],['OD600',t('Read growth response','读取生长响应')]]}/>,
 <JourneyFlow key="membrane" kicker={t('Control the measurement','控制测量条件')} nodes={[[t('Reagents','试剂'),t('Freshness and concentration','新鲜度与浓度')],[t('Optics','光谱'),t('Check overlap','排查重叠')],[t('Cells','细胞'),t('Growth phase and OD','生长阶段与 OD')]]}/>,
 <JourneyFlow key="next" kicker={t('A testable explanation','可检验的解释')} nodes={[[t('Repeat','重复'),t('Reproduce the phenotype','复现表型')],[t('Membrane','膜变化'),t('Resolve fluorescence sources','区分荧光来源')],['MCR-1',t('Test target dependence','检验靶点依赖性')]]}/>,
 ]} evidence={[<Suspense key="plates" fallback={<p role="status"><Copy>{t('Loading checkerboards…','正在加载棋盘图…')}</Copy></p>}><McrExplorer/></Suspense>]} evidenceLabels={[t('Explore the checkerboards','查看棋盘法实验')]}/>;}

const cultureSteps:JourneyStep[]=[
 {id:'application',label:t('Application','应用场景'),title:t('Start with a defined cell model.','先明确要解决哪一种培养问题。'),method:t('I reviewed scaffold-based 3D culture and separated adjustable material properties from evidence of cell survival, function and reproducibility.','我梳理基于支架的三维培养技术，将材料参数可调与细胞存活、功能和重复性的验证分开检查。'),result:t('The assessed business needed stronger biological validation across specific cell types and more complex models.','被评估企业仍需补强特定细胞类型及复杂模型中的生物学验证。'),next:t('Compare competing materials within that application.','在明确应用下比较竞品，而不只比较材料参数。')},
 {id:'competitors',label:t('Competitors','竞品比较'),title:t('Compare the complete product and workflow.','把产品与使用流程放在一起比较。'),method:t('I compared seven platforms, covering material composition, biological support, preparation, cell recovery and cost.','我比较七种平台的材料组成、生物学支持、制备、细胞回收与成本。'),result:t('The products deliver different units of value: a bottle of matrix, a gel-making kit or solid culture inserts.','不同产品提供的东西并不相同：可能是一瓶基质、一套成胶试剂，或固体培养嵌件。'),next:t('Translate price and handling differences into the cost of a usable result.','把价格和操作差异转化为一次有效实验的成本。')},
 {id:'workflow-cost',label:t('Workflow cost','工作流成本'),title:t('Follow the cost through the experiment.','沿着一次实验，追踪实际成本。'),method:t('I connected material choice to preparation, seeding, readout and cell recovery. The comparison needs consumables, staff time and repeat experiments.','我把材料选择与制备、接种、检测和细胞回收联系起来，比较时纳入耗材、人工时间和重做实验。'),result:t('Cost per valid well is a more useful decision measure than catalogue price per mL alone.','每个有效孔的成本，比单独比较每毫升目录价更能支持决策。'),next:t('Ask customer trials to establish the claimed workflow benefit.','通过客户试用，验证所声称的流程改善。')},
 {id:'investment',label:t('Diligence priorities','尽调重点'),title:t('Turn the evidence gap into a focused request.','把验证缺口变成明确的尽调要求。'),method:t('I drew together scientific literature, product documentation and market material for the investment team.','我综合科学文献、产品资料与市场材料，为投资团队形成技术与竞品评估。'),result:t('The priority was model-specific validation, a clear first application and evidence that customers would adopt and repeat the workflow.','优先补足特定模型的验证，明确首个应用，并检查客户采用和持续使用的证据。'),next:t('Request pilot validation, repeat-order evidence and the cost of supporting each workflow.','继续核查试用验证、复购，以及支持每套流程所需的投入。')},
];
export function CultureJourney(){return <ProjectJourney steps={cultureSteps} eyebrow={t('My diligence route','我的尽调路线')} title={t('From a material to an investment question.','从材料特点，走向投资判断。')} visuals={[
 <JourneyFlow key="model" kicker={t('The biological test','生物学检验')} nodes={[[t('Material','材料'),t('Adjustable properties','参数可调')],[t('Cell model','细胞模型'),t('Survival and function','存活与功能')],[t('Validation','验证'),t('Reproducible results','结果可重复')]]}/>,
 <JourneyFlow key="products" kicker={t('What is being compared?','究竟在比较什么？')} nodes={[[t('Formulation','配方'),t('Biological environment','生物学环境')],[t('Workflow','流程'),t('Preparation and recovery','制备与回收')],[t('Value','价值'),t('Usable experimental result','有效实验结果')]]}/>,
 <div className="journey-visual cost-visual" key="cost"><span className="visual-kicker"><Copy>{t('Cost per valid well','每个有效孔的成本')}</Copy></span><div className="cost-fraction"><strong><Copy>{t('Materials + time + repeats','材料 + 时间 + 重做')}</Copy></strong><span/><strong><Copy>{t('Wells that meet the assay criteria','达到实验标准的孔数')}</Copy></strong></div><p className="visual-note"><Copy>{t('A framework to test in customer workflows, not a measured price advantage.','用客户工作流验证这一口径，才能判断是否节省成本。')}</Copy></p></div>,
 <JourneyFlow key="decision" kicker={t('Evidence to request','需要补充的证据')} nodes={[[t('Pilot','试用'),t('A validated application','应用验证')],[t('Reorder','复购'),t('Repeated use','持续使用')],[t('Support','支持投入'),t('Cost to serve','服务成本')]]}/>,
 ]} evidence={[null,<CultureComparison key="comparison"/>]} evidenceLabels={[null,t('Compare the seven products','比较七种产品')]}/>;}
