'use client';
import { ProjectJourney, JourneyFlow, type JourneyStep } from './project-journey';
import { lazy, Suspense } from 'react';
const PetExplorer=lazy(()=>import('./pet-explorer').then(m=>({default:m.PetExplorer})));
const McrExplorer=lazy(()=>import('./mcr-explorer').then(m=>({default:m.McrExplorer})));
import { CultureComparison } from './culture-comparison';
import { MembraneProtocol } from './project-highlights';
import { SourceFigure } from './source-figure';
import { Copy } from './site-context';
import { t } from '@/lib/bilingual';

const petSteps:JourneyStep[]=[
 {id:'expression',label:t('Expression','表达条件'),title:t('Find a route to soluble protein.','先找到可用的表达条件。'),method:t('I compared constructs, bacterial strains and IPTG induction conditions at small scale, then checked the samples by SDS-PAGE before scaling up.','我在小规模培养中比较构建体、菌株和 IPTG 诱导条件，用 SDS-PAGE 检查样品后，再选择扩大培养的条件。'),result:t('The small-scale screen helped distinguish low expression from possible solubility problems.','小规模筛选帮助我区分表达不足与可能的可溶性问题。'),next:t('Follow the selected preparations through purification.','接着跟踪选定样品在纯化过程中的回收。')},
 {id:'purification',label:t('Purification','蛋白纯化'),title:t('Track where useful protein is recovered.','跟踪蛋白在哪一步被回收。'),method:t('I used His-tag affinity purification and size-exclusion chromatography to prepare CCH11 and TurboPETase for characterisation.','我使用 His 标签亲和纯化和体积排阻色谱，制备适合表征的 CCH11 与 TurboPETase。'),result:t('CCH11 reached approximately 3.9 mg total purified yield (CV record); TurboPETase remained limited by recovery and suspected solubility problems.','CCH11 纯化总回收量达到约 3.9 mg（简历记录）；TurboPETase 仍受回收不足及可溶性问题限制。'),next:t('Revisit the host and tag where recovery remains difficult.','对于回收仍困难的蛋白，继续考虑宿主和标签。')},
 {id:'host',label:t('Host & tag','宿主与标签'),title:t('Reconsider how the protein is made.','从表达体系寻找新的可能。'),method:t('I explored tag changes and a move from bacterial to yeast expression, followed by calorimetry.','我尝试调整标签、从细菌转向酵母表达，并开展后续量热分析。'),result:t('After the switch to yeast, the bursary report records improved CCH11 performance relative to the wild-type benchmark. Folding and post-translational modification remain possible explanations to test.','Bursary 总结记录：转向酵母后，CCH11 相对野生型基准的表现改善。折叠和翻译后修饰是可能的解释，仍需分别检验。'),next:t('Interpret the activity together with the preparation history.','将活性读数与蛋白的制备过程一起解释。')},
 {id:'characterisation',label:t('Activity readout','活性表征'),title:t('Connect an assay signal to the preparation.','把检测信号与蛋白样品联系起来。'),method:t('I worked with plate-reader and HPLC characterisation. The CCH11 traces compare test wells with controls for two substrate conditions.','我参与酶标仪与 HPLC 表征。CCH11 曲线比较了两种底物条件下实验孔和对照孔的响应。'),result:t('Test wells show a larger A550 decrease than controls. Quantitative enzyme comparisons also need matched inputs and product calibration.','实验孔的 A550 下降幅度大于对照孔；定量比较酶性能，还需匹配蛋白用量并校准产物。'),next:t('Use matched functional-protein inputs before attributing a difference to catalysis.','先匹配功能蛋白用量，再判断差异是否来自催化本身。')},
];
export function PetJourney(){return <ProjectJourney steps={petSteps} title={t('From expression to an activity readout.','从表达条件，走到活性读数。')} visuals={[
 <JourneyFlow key="expression" kicker={t('Small-scale screening','小规模筛选')} nodes={[[t('Construct','构建体'),t('Protein sequence and tag','序列与标签')],[t('Culture','培养'),t('Strain and induction','菌株与诱导')],['SDS-PAGE',t('Inspect the preparation','检查样品')]]}/>,
 <JourneyFlow key="purification" kicker={t('Protein recovery','蛋白回收')} nodes={[[t('His tag','His 标签'),t('Affinity purification','亲和纯化')],['SEC',t('Separate by size','按大小分离')],[t('Sample','样品'),t('≈3.9 mg CCH11','≈3.9 mg CCH11')]]} note={t('CCH11 recovery improved; TurboPETase prompted further optimisation.','CCH11 回收改善，TurboPETase 则推动了进一步优化。')}/>,
 <JourneyFlow key="host" kicker={t('A change in production conditions','改变制备条件')} nodes={[[t('Tag','标签'),t('Change the construct','调整构建体')],[t('Yeast','酵母'),t('Explore another host','尝试另一宿主')],[t('Calorimetry','量热'),t('Characterise the sample','表征样品')]]}/>,
 <JourneyFlow key="activity" kicker={t('A meaningful comparison','可解释的比较')} nodes={[[t('Test','实验孔'),t('Enzyme and substrate','酶与底物')],[t('Control','对照孔'),t('Resolve background','识别背景')],[t('Difference','响应差异'),t('Check input and calibration','检查用量与校准')]]}/>,
 ]} evidence={[null,null,null,<Suspense key="traces" fallback={<p role="status"><Copy>{t('Loading assay curves…','正在加载实验曲线…')}</Copy></p>}><PetExplorer/></Suspense>]} evidenceLabels={[null,null,null,t('Explore assay curves','查看实验曲线')]}/>;}

const mcrSteps:JourneyStep[]=[
 {id:'screening',label:t('Combination screen','联用筛选'),title:t('Use growth to identify the next question.','从生长筛选找到值得追问的组合。'),method:t('I ran MIC and checkerboard experiments with honokiol, pterostilbene and osthol alongside colistin, using the concentration matrix to select conditions for mechanistic work.','我开展和厚朴酚、紫檀芪、蛇床子素与黏菌素的 MIC、棋盘法实验，通过浓度矩阵筛选值得进一步研究的条件。'),result:t('The growth response guided the membrane experiments. A lower MIC alone could not establish a membrane mechanism or direct inhibition of MCR-1.','生长响应为膜实验提供方向；MIC 降低本身不能证明膜作用机制或对 MCR-1 的直接抑制。'),next:t('Check the resistance model independently through lipid A.','先用脂质 A 的独立读数核查耐药模型。')},
 {id:'lipid-a',label:t('MALDI / model','MALDI / 模型'),title:t('Verify the model before interpreting the response.','解释药物响应前，先验证实验体系。'),method:t('We used MALDI to monitor lipid A modification across the experimental conditions. Comparing modified and unmodified profiles helped check whether the intended MCR-1-associated state was present.','我们用 MALDI 监测不同实验条件下的脂质 A 修饰，通过比较修饰与未修饰谱型，核查体系是否呈现预期的 MCR-1 相关状态。'),result:t('Lipid A supplied an independent check on the model, alongside susceptibility measurements. It did not by itself identify the adjuvant target.','脂质 A 与药敏测量相互补充，为模型提供独立核查；它本身不能确定增效剂的作用靶点。'),next:t('Adapt the membrane protocols to the strains, induction conditions and compounds being tested.','再根据菌株、诱导条件及候选化合物调整膜检测方案。')},
 {id:'membrane',label:t('PI protocol','PI 方案'),title:t('Make the order of treatment part of the experiment.','把处理顺序纳入实验设计。'),method:t('I refined plate layout, OD normalisation, compound pretreatment and the timing of colistin addition. PI measurements followed nucleic-acid accessibility after membrane exclusion was compromised.','我调整板位布局、OD 归一化、化合物预处理与黏菌素加入时间，以 PI 的核酸结合信号观察细胞膜屏障受损后的变化。'),result:t('Honokiol pretreatment followed by colistin increased the PI signal in the bursary account. Controls and matched timing were essential for interpreting that response.','Bursary 总结记录：和厚朴酚预处理后加入黏菌素，PI 信号升高。对照设置与一致的时间安排，是解释这一响应的前提。'),next:t('Use a separate outer-membrane probe rather than assigning PI to the outer membrane.','外膜问题另用相应探针检验，不能把 PI 读数直接当作外膜特异信号。')},
 {id:'npn',label:t('NPN troubleshooting','NPN 排查'),title:t('Separate permeability from the fluorescence background.','区分通透性变化与荧光背景。'),method:t('For the new system I varied NPN freshness and concentration, checked compound spectral overlap, compared growth phases and normalised OD. The aim was to distinguish outer-membrane access from assay artefacts.','针对新的实验体系，我调整 NPN 新鲜度与浓度，排查化合物光谱重叠，比较生长阶段，并统一 OD，尝试区分外膜可及性与测量假象。'),result:t('NPN remained unreliable under the tested conditions. Mapping those interference sources defined which controls and readouts needed further development.','已测条件下 NPN 仍未获得可靠读数；排查明确了后续必须继续优化的干扰来源、对照与检测条件。'),next:t('Combine validated model checks with reproducible membrane readouts before making a causal claim.','将可靠的模型核查与可重复的膜读数结合后，再检验因果解释。')},
];
export function McrJourney(){return <ProjectJourney steps={mcrSteps} title={t('Validate the system. Develop the measurement.','验证实验体系，再建立可靠测量。')} visuals={[
 <JourneyFlow key="screen" kicker={t('A phenotype to investigate','需要追问的表型')} nodes={[[t('MIC','MIC'),t('Single compounds','单独化合物')],[t('Checkerboard','棋盘法'),t('Concentration pairs','浓度组合')],[t('Follow-up','后续实验'),t('Mechanistic question','机制问题')]]}/>,
 <MembraneProtocol key="maldi" kind="maldi"/>,<MembraneProtocol key="pi" kind="pi"/>,<MembraneProtocol key="npn" kind="npn"/>
 ]} evidence={[<Suspense key="plates" fallback={<p>Loading…</p>}><McrExplorer/></Suspense>,<SourceFigure key="lipid-a" src="/evidence/mcr-lipid-a.png" title={t('Lipid A profiles across induction conditions','不同诱导条件下的脂质 A 谱型')} legend={t('Source: End Project Summary, slide 6. Left and right boxes identify unmodified and modified lipid A regions. Conditions include 0%, 0.002%, 0.02% and 0.2% arabinose, and 0.5% glucose. Susceptibility labels are retained from the original figure.','来源：End Project Summary 第 6 页。左右框分别标示未修饰与修饰脂质 A 区域；条件包括 0%、0.002%、0.02%、0.2% 阿拉伯糖及 0.5% 葡萄糖。药敏标签保留原图记录。')} caption={t('Induction conditions change the lipid A profile. The original figure marks the 0.02% condition with an asterisk and the glucose condition as unknown; these qualifications are preserved. The comparison checks the model and does not demonstrate direct MCR-1 inhibition by an adjuvant.','诱导条件改变了脂质 A 谱型。原图对 0.02% 条件保留星号，并将葡萄糖条件标为未知；这些限定不作进一步推断。此比较用于核查模型，不能证明增效剂直接抑制 MCR-1。')}/>]} evidenceLabels={[t('Explore the checkerboards','查看棋盘法实验'),t('Inspect lipid A spectra','查看脂质 A 谱图')]}/>;}

const cultureSteps:JourneyStep[]=[
 {id:'application',label:t('Application','应用场景'),title:t('Which cell-culture problem is valuable enough to solve?','哪一种培养问题，值得优先解决？'),method:t('I reviewed scaffold-based 3D culture and separated adjustable material properties from evidence of cell survival, function and reproducibility.','我梳理基于支架的三维培养技术，将材料参数可调与细胞存活、功能和重复性的验证分开检查。'),result:t('The assessed business needed stronger biological validation across specific cell types and more complex models.','被评估企业仍需补强特定细胞类型及复杂模型中的生物学验证。'),next:t('Compare competing materials within that application.','在明确应用下比较竞品，而不只比较材料参数。')},
 {id:'competitors',label:t('Competitors','竞品比较'),title:t('What would make a customer switch from an established matrix?','客户为什么要从现有基质换过来？'),method:t('I compared seven platforms, covering material composition, biological support, preparation, cell recovery and cost.','我比较七种平台的材料组成、生物学支持、制备、细胞回收与成本。'),result:t('The products deliver different units of value: a bottle of matrix, a gel-making kit or solid culture inserts.','不同产品提供的东西并不相同：可能是一瓶基质、一套成胶试剂，或固体培养嵌件。'),next:t('Translate price and handling differences into the cost of a usable result.','把价格和操作差异转化为一次有效实验的成本。')},
 {id:'workflow-cost',label:t('Workflow cost','工作流成本'),title:t('Would the technical advantage lower the cost of a valid result?','技术优势，能否降低一次有效实验的成本？'),method:t('I connected material choice to preparation, seeding, readout and cell recovery. The comparison needs consumables, staff time and repeat experiments.','我把材料选择与制备、接种、检测和细胞回收联系起来，比较时纳入耗材、人工时间和重做实验。'),result:t('Cost per valid well is a more useful decision measure than catalogue price per mL alone.','每个有效孔的成本，比单独比较每毫升目录价更能支持决策。'),next:t('Ask customer trials to establish the claimed workflow benefit.','通过客户试用，验证所声称的流程改善。')},
 {id:'investment',label:t('Diligence priorities','尽调重点'),title:t('Which missing evidence would change the investment judgement?','补齐哪项证据，才会改变投资判断？'),method:t('I drew together scientific literature, product documentation and market material for the investment team.','我综合科学文献、产品资料与市场材料，为投资团队形成技术与竞品评估。'),result:t('The priority was model-specific validation, a clear first application and evidence that customers would adopt and repeat the workflow.','优先补足特定模型的验证，明确首个应用，并检查客户采用和持续使用的证据。'),next:t('Request pilot validation, repeat-order evidence and the cost of supporting each workflow.','继续核查试用验证、复购，以及支持每套流程所需的投入。')},
];
export function CultureJourney(){return <ProjectJourney steps={cultureSteps} eyebrow={t('My diligence route','我的尽调路线')} title={t('From a material to an investment question.','从材料特点，走向投资判断。')} visuals={[
 <JourneyFlow key="model" kicker={t('The biological test','生物学检验')} nodes={[[t('Material','材料'),t('Adjustable properties','参数可调')],[t('Cell model','细胞模型'),t('Survival and function','存活与功能')],[t('Validation','验证'),t('Reproducible results','结果可重复')]]}/>,
 <JourneyFlow key="products" kicker={t('What is being compared?','究竟在比较什么？')} nodes={[[t('Formulation','配方'),t('Biological environment','生物学环境')],[t('Workflow','流程'),t('Preparation and recovery','制备与回收')],[t('Value','价值'),t('Usable experimental result','有效实验结果')]]}/>,
 <div className="journey-visual cost-visual" key="cost"><span className="visual-kicker"><Copy>{t('Cost per valid well','每个有效孔的成本')}</Copy></span><div className="cost-fraction"><strong><Copy>{t('Materials + time + repeats','材料 + 时间 + 重做')}</Copy></strong><span/><strong><Copy>{t('Wells that meet the assay criteria','达到实验标准的孔数')}</Copy></strong></div><p className="visual-note"><Copy>{t('A framework to test in customer workflows, not a measured price advantage.','用客户工作流验证这一口径，才能判断是否节省成本。')}</Copy></p></div>,
 <JourneyFlow key="decision" kicker={t('Evidence to request','需要补充的证据')} nodes={[[t('Pilot','试用'),t('A validated application','应用验证')],[t('Reorder','复购'),t('Repeated use','持续使用')],[t('Support','支持投入'),t('Cost to serve','服务成本')]]}/>,
 ]} evidence={[null,<CultureComparison key="comparison"/>]} evidenceLabels={[null,t('Compare the seven products','比较七种产品')]}/>;}
