'use client';
import {useEffect,useState} from 'react';
type Paper={id:string;title:string;code:string;year:number;unit:number;component:string;qp?:string;ms?:string;missing_figures?:boolean};
export function CiePapers({zh}:{zh:boolean}){
 const [papers,setPapers]=useState<Paper[]>([]),[year,setYear]=useState(''),[component,setComponent]=useState(''),[limit,setLimit]=useState(20),[error,setError]=useState(false),[fileCount,setFileCount]=useState(0);
 useEffect(()=>{let active=true;fetch('/question-bank/cie-papers.json').then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{papers:Paper[];fileCount:number}>}).then(d=>{if(active){setPapers(d.papers);setFileCount(d.fileCount)}}).catch(()=>{if(active)setError(true)});return()=>{active=false}},[]);
 const t=(en:string,cn:string)=>zh?cn:en;
 const filtered=papers.filter(p=>(!year||String(p.year)===year)&&(!component||p.component===component));
 return <details className="qb-random"><summary>{t('Past papers · all files','历年原卷 · 全部文件')} {fileCount>0&&`(${fileCount})`}</summary><div className="qb-random-controls"><select aria-label={t('Archive year','原卷年份')} value={year} onChange={e=>{setYear(e.target.value);setLimit(20)}}><option value="">{t('All years','全部年份')}</option>{[...new Set(papers.map(p=>p.year))].sort((a,b)=>b-a).map(y=><option key={y}>{y}</option>)}</select><select aria-label={t('Archive component','原卷卷号')} value={component} onChange={e=>{setComponent(e.target.value);setLimit(20)}}><option value="">{t('All components','全部卷号')}</option>{[...new Set(papers.map(p=>p.component))].sort().map(c=><option key={c}>{c}</option>)}</select></div><p className="qb-random-note">{t('Download question papers and mark schemes separately. Missing files are indicated.','试卷和答案可单独下载，缺少的文件会标注。')}</p>{error?<p role="alert">{t('Could not load papers. Please refresh.','原卷暂时没加载出来，请刷新。')}</p>:<ul className="qb-paper-list">{filtered.slice(0,limit).map(p=><li key={p.id}><span>{p.title}{p.missing_figures&&<small> · {t('Some figures omitted in source','原卷部分图表缺失')}</small>}</span><span>{p.qp?<a href={p.qp} target="_blank" rel="noreferrer">{t('Question paper','试卷')}</a>:<small>{t('QP unavailable','暂无试卷')}</small>}{p.ms?<a href={p.ms} target="_blank" rel="noreferrer">{t('Mark scheme','答案')}</a>:<small>{t('MS unavailable','暂无答案')}</small>}</span></li>)}</ul>}{filtered.length>limit&&<button onClick={()=>setLimit(limit+30)}>{t('Show more','再看一些')}</button>}</details>;
}
