'use client';
import { useState } from 'react';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import records from '@/lib/mcr-plates.json';
const maxOD = Math.max(...records.plates.flatMap(p=>p.values.flat()));
export function McrExplorer() {
 const [id,setId]=useState(records.plates[0].id), [cell,setCell]=useState([0,0]);
 const plate=records.plates.find(p=>p.id===id)!;
 return <section className="interactive-panel" aria-label="Checkerboard growth explorer"><div className="explorer-top"><div><p className="eyebrow">Recorded growth assays</p><h2>Read the checkerboard.</h2></div><Select value={id} onValueChange={v=>{if(v){setId(v);setCell([0,0]);}}}><SelectTrigger aria-label="Choose experiment"><SelectValue>{plate.compound} / {plate.date} / {plate.strainLabel}</SelectValue></SelectTrigger><SelectContent>{records.plates.map(p=><SelectItem value={p.id} key={p.id}>{p.compound} / {p.date} / {p.strainLabel}</SelectItem>)}</SelectContent></Select></div>
 <p>Select an experiment, then select a well to read its concentrations and OD600. Colours use the same scale across all experiments.</p>
 <div className="heatmap-layout"><div><p className="small muted">Columns: colistin (µg/mL) · Rows: {plate.compound} (µg/mL)</p><div className="data-scroll heatmap-scroll"><table className="heatmap"><caption>{plate.compound}, {plate.strainLabel}, {plate.date}: OD600</caption><thead><tr><th scope="col">µg/mL</th>{plate.colistinConcentrations.map(v=><th scope="col" key={v}>{v}</th>)}</tr></thead><tbody>{plate.values.map((row,i)=><tr key={i}><th scope="row">{plate.adjuvantConcentrations[i]}</th>{row.map((v,j)=>{const t=Math.max(0,v/maxOD);return <td key={j}><button type="button" aria-pressed={cell[0]===i&&cell[1]===j} aria-label={`${plate.compound} ${plate.adjuvantConcentrations[i]}, colistin ${plate.colistinConcentrations[j]} micrograms per millilitre: OD600 ${v}`} onClick={()=>setCell([i,j])} style={{background:`rgb(${Math.round(249-151*t)},${Math.round(245-190*t)},${Math.round(255-111*t)})`,color:t>.5?'white':'#302640'}}>{v.toFixed(2)}</button></td>;})}</tr>)}</tbody></table></div><div className="heat-scale"><span>0</span><i/><span>{maxOD.toFixed(2)} OD600</span></div></div>
 <aside className="well-detail" aria-live="polite"><span className="eyebrow">Selected well</span><strong>{plate.values[cell[0]][cell[1]].toFixed(3)}</strong><span>OD600</span><dl><dt>{plate.compound}</dt><dd>{plate.adjuvantConcentrations[cell[0]]} µg/mL</dd><dt>Colistin</dt><dd>{plate.colistinConcentrations[cell[1]]} µg/mL</dd><dt>Recorded strain</dt><dd>{plate.strainLabel}</dd></dl></aside></div>
 <p className="interpretation">These are exploratory endpoint readouts, not calculated FIC indices. Each cell represents one recorded well. The displayed strain labels do not by themselves establish MCR-1 expression.</p><details><summary>Controls, processing and source</summary><p>{plate.processing} The source figures corroborate µg/mL units. MIC thresholds and replicate structure have not been established for this public comparison. Non-monotonic wells and differences between records need to be resolved before a formal synergy estimate.</p><p className="small muted">Source: {plate.source}, {plate.sheet}, {plate.range}.</p><div className="data-scroll"><table><caption>Recorded control wells</caption><thead><tr><th>Row</th><th>DMSO</th><th>Growth</th><th>Empty</th><th>Sterility</th></tr></thead><tbody>{plate.controls.map((r,i)=><tr key={i}><th>{i+1}</th><td>{r.DMSO}</td><td>{r.growth}</td><td>{r.empty}</td><td>{r.sterility}</td></tr>)}</tbody></table></div><a className="text-link" href="/data/mcr-checkerboards.csv" download>Download recorded checkerboards (CSV) ↓</a></details></section>;
}
