'use client';
import { useState } from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import traces from '@/lib/pet-traces.json';
export function PetExplorer() {
 const [substrate, setSubstrate] = useState('DIES');
 const columns = substrate === 'DIES' ? [1,2] : [3,4];
 const wells = ['D','E','F'].flatMap(row => columns.map((column, i) => ({ key: `${row}${column}`, test: i === 1 })));
 return <section className="interactive-panel" aria-label="CCH11 assay trace explorer"><div className="explorer-top"><div><p className="eyebrow">Recorded experiment / 26 June 2025</p><h2>Inspect the individual wells.</h2></div><Tabs value={substrate} onValueChange={v=>setSubstrate(String(v))}><TabsList aria-label="Substrate condition"><TabsTrigger value="DIES">DIES</TabsTrigger><TabsTrigger value="BHET">BHET</TabsTrigger></TabsList></Tabs></div>
 <p>Absorbance at 550 nm. Each line is one well; the labels follow the retained CCH11 worksheet.</p><div className="chart-axis-label">Absorbance (A550)</div><div className="trace-chart" role="img" aria-label={`${substrate}: three test wells and three control wells, absorbance over time. The full values are available below.`}><ResponsiveContainer width="100%" height="100%"><LineChart data={traces} margin={{top:15,right:20,left:0,bottom:20}}><CartesianGrid stroke="#e3e9ee" strokeDasharray="3 3"/><XAxis dataKey="time" type="number" domain={[0,100]} tickFormatter={v=>Number(v).toFixed(0)} label={{value:'Time (min)',position:'insideBottom',offset:-12}}/><YAxis domain={[0,1.2]} width={45}/><Tooltip labelFormatter={v=>`${Number(v).toFixed(2)} min`} formatter={(v,n)=>[Number(v).toFixed(4),n]}/>{wells.map((w,i)=><Line key={w.key} dataKey={w.key} name={`${w.test?'Test':'Control'} ${w.key}`} stroke={w.test?['#235C8B','#2B76AA','#498BAC'][Math.floor(i/2)]:'#8798A6'} strokeDasharray={w.test?undefined:'5 4'} strokeWidth={w.test?2:1.5} dot={false} type="linear" isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div>
 <div className="trace-legend"><span><i className="legend-test"/> Test wells {wells.filter(w=>w.test).map(w=>w.key).join(', ')}</span><span><i className="legend-control"/> Control wells {wells.filter(w=>!w.test).map(w=>w.key).join(', ')}</span></div><p className="interpretation">The test wells show a larger decrease than their controls. These are recorded assay signals, without conversion to product concentration or active-enzyme normalisation.</p>
 <details><summary>Conditions, full values and source</summary><p>100 time points; approximately 0 to 99 minutes; recorded temperature 39.7 to 40.5 °C. Three wells per condition do not establish three independent protein preparations. DIES is retained as the worksheet label. The reaction recipe and calibration are incomplete, so these curves are not reported as kcat or PET degradation rates.</p><p className="small muted">Retained project workbook, 26 June 2025: CCH11 sheet, B2:CW14; condition mapping P19:P23. The instrument record supports the displayed values, but does not establish sole acquisition by Bill.</p><a className="text-link" href="/data/pet-raw-traces.csv" download>Download all recorded traces (CSV) ↓</a><div className="data-scroll"><table><caption>{substrate} recorded absorbance values</caption><thead><tr><th>Time (min)</th>{wells.map(w=><th key={w.key}>{w.key}</th>)}</tr></thead><tbody>{traces.map((r,i)=><tr key={i}><th>{r.time.toFixed(2)}</th>{wells.map(w=><td key={w.key}>{Number(r[w.key as keyof typeof r]).toFixed(4)}</td>)}</tr>)}</tbody></table></div></details></section>;
}
