'use client';
import { Copy } from './site-context';
import { t } from '@/lib/bilingual';

export function EfficiencyComparison(){return <figure className="efficiency-panel" id="efficiency"><div><p className="eyebrow"><Copy>{t('Why pursue HuBisCO? / Theoretical model','为什么研究 HuBisCO？/ 理论模型')}</Copy></p><h3><Copy>{t('About 40% more product for the same energy budget.','相同能量预算下，理论产物收益约提高 40%。')}</Copy></h3><p><Copy>{t('The proposal aims to avoid the costly 2-PG salvage route associated with photorespiration.','这一路线旨在避免光呼吸中代价较高的 2-PG 回收过程。')}</Copy></p></div><div className="efficiency-chart" role="img" aria-label="Modelled relative product yield: conventional CBB 100, proposed HuBisCO 140"><div><span>CBB</span><i style={{width:'71.43%'}}/><b>100</b></div><div className="proposed"><span>HuBisCO</span><i style={{width:'100%'}}/><b>≈140</b></div><p><Copy>{t('Relative product yield · CBB with photorespiration = 100','相对产物收益 · 含光呼吸的 CBB 路线 = 100')}</Copy></p></div><figcaption><Copy>{t('Source: project dissertation, Figure 3 and its stoichiometric model. Assumptions: 25% oxygenation events; 1 NAD(P)H = 2.5 ATP equivalents. This is a pathway-level prediction, not measured enzyme activity or plant yield. HuBP turnover and the complete pathway remain unverified.','依据：项目论文图 3 及其化学计量模型。假设：25% 的催化事件为加氧反应；1 NAD(P)H 按 2.5 ATP 当量计算。这是代谢路线层面的预测，不是实测酶活或植物增产结果；HuBP 催化及完整路线仍待验证。')}</Copy></figcaption></figure>;}

export function PetOutcome(){return <section className="outcome-panel"><div className="yield-vial" aria-hidden="true"><div className="vial-cap"/><div className="vial-glass"><i/><span>CCH11</span></div></div><div><p className="eyebrow"><Copy>{t('Expression became a usable preparation','从表达瓶颈到可用样品')}</Copy></p><h2>≈3.9 <small>mg</small></h2><p><Copy>{t('Total purified CCH11 recovered, as recorded in my CV. His-tag affinity purification and SEC brought production to the milligram scale.','简历记录的 CCH11 纯化总回收量。通过 His 标签亲和纯化与 SEC，制备达到毫克级。')}</Copy></p><p className="small muted"><Copy>{t('The host change from E. coli to S. cerevisiae also improved the CCH11 activity comparison with the wild-type benchmark in my bursary report. This was a qualitative observation; it does not establish a fold improvement or a post-translational mechanism.','Bursary 总结还记录：由大肠杆菌转向酿酒酵母后，CCH11 相对野生型基准的活性表现得到改善。这是定性观察，不能据此给出提升倍数或认定翻译后修饰机制。')}</Copy></p></div></section>;}

export function MembraneProtocol({kind='overview'}:{kind?:'overview'|'pi'|'npn'|'maldi'}){
 return <div className={`membrane-workbench membrane-${kind}`}><div className="membrane-diagram" aria-hidden="true"><div className="membrane-probe">NPN</div><div className="membrane-layer outer">{Array.from({length:14},(_,i)=><i key={i}/>)}</div><span className="membrane-space">LPS · lipid A</span><div className="membrane-layer inner">{Array.from({length:14},(_,i)=><i key={i}/>)}</div><div className="membrane-dna">DNA <b>PI</b></div></div><div className="membrane-key"><div><b>NPN</b><span><Copy>{t('Outer-membrane access; compound background and optical interference must be controlled.','反映外膜疏水区域的可及性；需排除化合物背景与光谱干扰。')}</Copy></span></div><div><b>PI</b><span><Copy>{t('Nucleic-acid signal after loss of membrane exclusion; pretreatment and addition timing matter.','细胞膜屏障受损后产生核酸结合信号；预处理与加药时间影响读数。')}</Copy></span></div><div><b>MALDI</b><span><Copy>{t('Monitor lipid A modification to check the experimental model before interpreting the adjuvant response.','监测脂质 A 修饰，先核查实验模型，再解释增效响应。')}</Copy></span></div></div><p className="small muted"><Copy>{t('Conceptual assay map; animation does not represent a measured trajectory or spectrum.','检测原理示意；动画不表示实测运动轨迹或质谱。')}</Copy></p></div>;
}
