'use client';
import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {ArrowLeft,ArrowRight,Check,Download,Plus,Search,SlidersHorizontal,X,BookOpen,ChevronUp,ChevronDown} from 'lucide-react';
import {useSite,SiteLink} from './site-context';
import {banks,loadCatalog,resolveSelection,removeSelection,selectedMarks,expectedMinutes,qualification,type Bank,type Catalog,type Question} from '@/lib/question-bank';
import './question-bank.css';
import {reportDownload,downloadEventId} from '@/lib/download-analytics';
import {PdfPreview} from './pdf-preview';
import {RandomPaper} from './random-paper';
import {TopicPicker} from './topic-picker';

const paperLabel=(q:Question)=>q.bank==='edexcel'?`Unit ${q.unit} · ${q.paper_title}`:q.paper_title;
export function QuestionBank(){
 const {locale}=useSite();const zh=locale==='zh';const t=(en:string,cn:string)=>zh?cn:en;
 const [bank,setBank]=useState<Bank|null>(null),[catalog,setCatalog]=useState<Catalog|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[year,setYear]=useState(''),[topics,setTopics]=useState<string[]>([]),[level,setLevel]=useState(''),[unit,setUnit]=useState(''),[kind,setKind]=useState('leaf'),[more,setMore]=useState(false),[skill,setSkill]=useState(''),[ids,setIds]=useState<string[]>([]),[ready,setReady]=useState(false),[limit,setLimit]=useState(30),[cartOpen,setCartOpen]=useState(false),[busy,setBusy]=useState('');
 const [downloadFile,setDownloadFile]=useState<{url:string;name:string}|null>(null);
 useEffect(()=>()=>{if(downloadFile)URL.revokeObjectURL(downloadFile.url);},[downloadFile]);
 const [preview,setPreview]=useState<Question|null>(null),[role,setRole]=useState<'qp'|'ms'>('qp'),[previewUrl,setPreviewUrl]=useState(''),[previewError,setPreviewError]=useState('');const dialog=useRef<HTMLDialogElement>(null);const cartDialog=useRef<HTMLDialogElement>(null);const prevFocus=useRef<HTMLElement|null>(null);
 useEffect(()=>{const value=new URLSearchParams(location.search).get('bank');if(value&&value in banks)setBank(value as Bank);},[]);
 useEffect(()=>{if(!bank)return;let cancelled=false;setReady(false);setCatalog(null);setError('');setQuery('');setYear('');setTopics([]);setLevel('');setUnit('');setSkill('');setKind('leaf');loadCatalog(bank).then(data=>{if(cancelled)return;setCatalog(data);try{const stored=JSON.parse(localStorage.getItem('public-biology-'+bank)||'[]');setIds(Array.isArray(stored)?stored.filter(x=>typeof x==='string'&&data.questions.some(q=>q.id===x)):[]);}catch{setIds([]);}setReady(true);}).catch(()=>{if(!cancelled)setError(t('The question bank could not load. Please refresh and try again.','题库暂时没加载出来，刷新试试。'));});return()=>{cancelled=true;};},[bank]);
 useEffect(()=>{if(bank&&ready)try{localStorage.setItem('public-biology-'+bank,JSON.stringify(ids));}catch{}},[ids,bank,ready]);
 useEffect(()=>{setLimit(30);},[query,year,topics,level,unit,kind,skill]);
 useEffect(()=>{const el=cartDialog.current;if(!el)return;if(cartOpen&&!el.open)el.showModal();else if(!cartOpen&&el.open)el.close();},[cartOpen]);
 useEffect(()=>{if(!cartOpen)return;const mq=matchMedia('(min-width:851px)');const close=()=>{if(mq.matches)setCartOpen(false);};mq.addEventListener('change',close);return()=>mq.removeEventListener('change',close);},[cartOpen]);
 useEffect(()=>{if(!cartOpen&&!preview)return;const before=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=before;};},[cartOpen,!!preview]);
 useEffect(()=>{if(preview){prevFocus.current=document.activeElement as HTMLElement;dialog.current?.showModal();}else{dialog.current?.close();prevFocus.current?.focus();}},[preview?.id]);
 useEffect(()=>{if(!preview||!catalog)return;let active=true,url='';setPreviewUrl('');setPreviewError('');import('@/lib/question-pdf').then(m=>m.createQuestionPdf(catalog,[preview.id],role,undefined,true)).then(bytes=>{if(!active)return;url=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:'application/pdf'}));setPreviewUrl(url);}).catch(()=>{if(active)setPreviewError(t('Preview unavailable. Please try again.','预览暂时打不开，请重试。'));});return()=>{active=false;if(url)URL.revokeObjectURL(url);};},[preview,catalog,role]);
 const selected=useMemo(()=>{try{return catalog?resolveSelection(ids,catalog.questions):[];}catch{return[];}},[ids,catalog]);const marks=catalog?selectedMarks(selected,catalog.questions):0;
 const results=useMemo(()=>{const terms=query.toLowerCase().trim().split(/\s+/).filter(Boolean);return (catalog?.questions||[]).filter(q=>(kind==='major'?q.kind==='major':q.is_leaf)&&(!year||String(q.year)===year)&&(!unit||String(q.unit)===unit)&&(!level||qualification(q)===level)&&(!topics.length||topics.some(t=>q.topic_ids?.includes(t)))&&(!skill||q.skills?.includes(skill))&&terms.every(term=>[q.text,q.summary,q.label,q.paper_title,...q.topics||[],...q.chapters||[]].join(' ').toLowerCase().includes(term))).sort((a,b)=>b.year-a.year||a.paper_title.localeCompare(b.paper_title)||a.label.localeCompare(b.label,undefined,{numeric:true}));},[catalog,query,year,unit,topics,level,kind,skill]);
 function choose(next:Bank){setDownloadFile(null);setBank(next);history.replaceState(null,'',location.pathname+'?bank='+next);}
 function add(q:Question){if(!catalog)return;try{const next=resolveSelection([...ids,q.id],catalog.questions);if(next.length>100)throw Error(t('Choose up to 100 question groups at a time.','一次最多选100个题目单元。'));setIds(next.map(x=>x.id));setError('');}catch(e){setError((e as Error).message);}}
 function remove(id:string){if(catalog)setIds(removeSelection(ids,id,catalog.questions));}
 function move(index:number,step:number){const next=selected.map(q=>q.id);const target=index+step;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setIds(next);}
 async function download(type:'qp'|'ms'){if(!catalog||!bank||busy)return;const started=performance.now(),eventId=downloadEventId();const report=(status:'success'|'error',bytes=0)=>reportDownload({event_id:eventId,bank,kind:type,status,bytes,duration_ms:Math.min(3600000,Math.round(performance.now()-started)),questions:selected.length});setBusy(t('Generating PDF…','正在生成 PDF…'));setError('');try{const fresh=await loadCatalog(bank);const {createQuestionPdf}=await import('@/lib/question-pdf');const bytes=await createQuestionPdf(fresh,ids,type,(done,total)=>setBusy(`${done} / ${total}`));const url=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download=`${bank}-biology-${type==='qp'?'questions':'answers'}.pdf`;setDownloadFile({url,name:a.download});document.body.appendChild(a);a.click();a.remove();report('success',bytes.byteLength);}catch(e){report('error');setError(t('Download failed. Please refresh your selection and try again.','下载没成功，请刷新选题后再试。')+' '+(e as Error).message);}finally{setBusy('');}}
 const selectionPanel=(<><div className="qb-cart-heading"><h2>{t('Your selection','已选题目')}</h2><button className="qb-mobile-close" aria-label={t('Close selection','关闭选题')} onClick={()=>setCartOpen(false)}><X size={20}/></button></div><div className="qb-total"><strong>{marks}</strong><span>{t('marks','分')} · {selected.length} {t('groups','个选题')} · {t('~','约 ')}{catalog?expectedMinutes(selected,catalog.questions):0} {t('min','分钟')}</span></div>{!selected.length?<p className="qb-empty">{t('No questions selected','还没有选题')}</p>:<ol className="qb-selected">{selected.map((q,i)=><li key={q.id}><span><b>{i+1}.</b> {paperLabel(q)} · {q.label}</span><div><button aria-label={`${t('Move up','上移')} ${i+1}`} disabled={i===0} onClick={()=>move(i,-1)}><ChevronUp size={16}/></button><button aria-label={`${t('Move down','下移')} ${i+1}`} disabled={i===selected.length-1} onClick={()=>move(i,1)}><ChevronDown size={16}/></button><button aria-label={`${t('Remove','移除')} ${q.label}`} onClick={()=>remove(q.id)}><X size={16}/></button></div></li>)}</ol>}
 <div className="qb-downloads" aria-busy={!!busy}><button className="qb-primary" disabled={!selected.length||!!busy} onClick={()=>download('qp')}><Download size={17}/>{t('Questions PDF','下载题目 PDF')}</button><button disabled={!selected.length||!!busy} onClick={()=>download('ms')}><Download size={17}/>{t(bank==='esat'?'Answer key':'Mark scheme',bank==='esat'?'下载答案':'下载答案 / MS')}</button>{busy&&<span role="status">{busy}</span>}{downloadFile&&!busy&&<div className="qb-ready-actions"><a href={downloadFile.url} download={downloadFile.name}>{t('Save PDF','保存 PDF')}</a><a href={downloadFile.url} target="_blank" rel="noreferrer">{t('Open PDF','打开 PDF')}</a><small>{t('If saving does not start, open the PDF and use your browser’s share or save menu.','若没有开始下载，打开 PDF 后可用浏览器的分享或保存功能。')}</small></div>}</div><small>{t('Times are estimates based on exam timings. Your selection stays on this device.','用时按考试时长估算，选题保留在当前设备。')}</small><small className="qb-privacy">{t('Anonymous export counts help maintain this tool. No login or visitor tracking.','匿名统计导出次数和文件大小，用于维护题库，不记录访客身份。')}</small></>);
 const options=(field:'chapters'|'skills')=>[...new Set((catalog?.questions||[]).flatMap(q=>q[field]||[]))].sort();
 return <main className="qb" style={{'--qb-base':bank?banks[bank].color:'#23645d','--qb-bright':bank?banks[bank].bright:'#87c6b8'} as CSSProperties}>
 <div className="qb-top"><SiteLink href="/tools"><ArrowLeft size={16}/>{t('Tools','工具')}</SiteLink><span>Biology Question Bank</span></div>
 {!bank?<section className="qb-entry"><span className="qb-kicker">BIOLOGY QUESTION BANK</span><h1>{t('Biology question bank','生物题库')}</h1><p>{t('Filter past-paper questions by topic, or build a paper by time or marks.','按知识点选题，或按时间、分数组卷。题目和答案可分别导出。')}</p><div className="qb-banks">{(Object.keys(banks) as Bank[]).map(key=><button key={key} onClick={()=>choose(key)} style={{'--qb-base':banks[key].color,'--qb-bright':banks[key].bright} as CSSProperties}><BookOpen size={28}/><h2>{banks[key].name}</h2><span>{banks[key].caption}</span><strong>{t('Choose questions','开始选题')} <ArrowRight size={17}/></strong></button>)}</div><p className="qb-source-note">{t('ESAT practice includes past NSAA Biology questions.','ESAT 题库使用 NSAA 历年生物题。')}</p></section>:<>
 <div className="qb-bankbar"><h1>{banks[bank].name}</h1><div className="qb-switch" aria-label={t('Question bank','题库')}>{(Object.keys(banks) as Bank[]).map(key=><button key={key} aria-pressed={bank===key} onClick={()=>choose(key)}>{banks[key].name}</button>)}</div></div>
 <div className="qb-layout"><section className="qb-main"><div className="qb-filters"><label className="qb-search"><Search size={19}/><input aria-label={t('Search questions','搜索题目')} placeholder={t('Topic or keyword','搜索考点或关键词')} value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="qb-filter-row">{bank!=='esat'&&<select aria-label={t('Level','阶段')} value={level} onChange={e=>setLevel(e.target.value)}><option value="">AS & AL</option><option value="AS">AS</option><option value="AL">AL</option></select>}<select aria-label={t('Year','年份')} value={year} onChange={e=>setYear(e.target.value)}><option value="">{t('All years','全部年份')}</option>{[...new Set(catalog?.questions.map(q=>q.year))].sort((a,b)=>b-a).map(y=><option key={y}>{y}</option>)}</select><button className="qb-subtle" aria-expanded={more} onClick={()=>setMore(!more)}><SlidersHorizontal size={16}/>{t('More','更多筛选')}</button></div>{more&&<div className="qb-filter-row">{bank!=='esat'&&<><select aria-label={t('Paper or unit','单元或试卷')} value={unit} onChange={e=>setUnit(e.target.value)}><option value="">{t('All papers','全部试卷')}</option>{[...new Set(catalog?.questions.map(q=>q.unit))].sort().map(u=><option key={u} value={u}>{bank==='aqa'||bank==='cie'?'Paper':'Unit'} {u}</option>)}</select><select aria-label={t('Question size','题目层级')} value={kind} onChange={e=>setKind(e.target.value)}><option value="leaf">{bank==='cie'?t('All questions','全部题目'):t('Individual questions','按小题选')}</option><option value="major">{bank==='cie'?t('Structured questions','结构题'):t('Whole questions','按大题选')}</option></select></>}<select aria-label={t('Skill','技能')} value={skill} onChange={e=>setSkill(e.target.value)}><option value="">{t('All skills','全部技能')}</option>{options('skills').map(s=><option key={s}>{s}</option>)}</select><button className="qb-subtle" onClick={()=>{setQuery('');setYear('');setTopics([]);setLevel('');setUnit('');setSkill('');}}>{t('Reset','清除筛选')}</button></div>}</div>
 {catalog&&<><TopicPicker nodes={catalog.taxonomy||[]} value={topics} onChange={setTopics} zh={zh}/><RandomPaper key={bank} questions={catalog.questions} zh={zh} year={year} unit={unit} topics={topics} qualification={level} onSelect={setIds}/></>}
 <div className="qb-resultbar"><span>{catalog?`${results.length} ${t('questions','道题')}`:t('Loading…','正在加载…')}</span>{bank==='esat'&&<small>{t('Historical NSAA questions','NSAA 历史题')}</small>}</div>
 {error&&<p className="qb-error" role="alert">{error}</p>}
 <div className="qb-results">{results.slice(0,limit).map(q=>{const added=selected.some(s=>q.leaves.every(id=>s.leaves.includes(id)));return <article key={q.id}><button className="qb-question" onClick={()=>{setRole('qp');setPreview(q);}}><div className="qb-question-meta"><span>{paperLabel(q)} · {q.label}</span><span>{q.marks} {t(q.marks===1?'mark':'marks','分')} · {t('~','约 ')}{q.expected_seconds/60} {t('min','分钟')}</span></div><h3>{q.summary||q.topics?.[0]||q.label}</h3><div className="qb-tags">{(q.topics||[]).slice(0,2).map(tag=><span key={tag}>{tag}</span>)}{q.historical_extension&&<span>{t('Historical extension','历史拓展')}</span>}</div></button><button className={'qb-add'+(added?' added':'')} aria-label={`${added?t('Selected','已选'):t('Add','加入')} ${paperLabel(q)} ${q.label}`} disabled={added} onClick={()=>add(q)}>{added?<Check size={19}/>:<Plus size={19}/>}</button></article>;})}{catalog&&!results.length&&<div className="qb-empty">{t('No matches. Try another topic or year.','没有找到，换个关键词或年份试试。')}</div>}</div>{results.length>limit&&<button className="qb-more" onClick={()=>setLimit(limit+30)}>{t('Show more','加载更多')}</button>}
 </section><aside className="qb-cart qb-cart-desktop" aria-label={t('Selected questions','已选题目')}>{selectionPanel}</aside><dialog className="qb-cart qb-cart-dialog" ref={cartDialog} aria-label={t('Selected questions','已选题目')} onCancel={()=>setCartOpen(false)} onClick={e=>{if(e.target!==e.currentTarget)return;const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)setCartOpen(false);}}>{selectionPanel}</dialog></div>
 <button className="qb-mobile-cart qb-primary" aria-haspopup="dialog" aria-expanded={cartOpen} onClick={()=>setCartOpen(true)}>{t('Selected','已选')} {selected.length} · {marks} {t('marks','分')} <ArrowRight size={17}/></button>
 </>}
 <dialog className="qb-preview" ref={dialog} onCancel={()=>setPreview(null)}><div className="qb-preview-head"><strong>{preview&&paperLabel(preview)} · {preview?.label}</strong><button aria-label={t('Close preview','关闭预览')} onClick={()=>setPreview(null)}><X size={22}/></button></div><div className="qb-preview-tabs"><button aria-pressed={role==='qp'} onClick={()=>setRole('qp')}>{t('Question','题目')}</button><button aria-pressed={role==='ms'} onClick={()=>setRole('ms')}>{t(bank==='esat'?'Answer key':'Mark scheme',bank==='esat'?'答案字母':'答案 / MS')}</button>{preview&&<button className="qb-primary" onClick={()=>{add(preview);setPreview(null);}}><Plus size={16}/>{t('Add','加入选题')}</button>}</div>{previewError?<p role="alert">{previewError}</p>:previewUrl?<><PdfPreview url={previewUrl} loading={t('Loading original page…','正在加载原题…')} error={t('Preview unavailable. Open the PDF below.','预览暂时打不开，可以用下面的链接打开 PDF。')}/><a href={previewUrl} target="_blank" rel="noreferrer">{t('Open PDF','单独打开 PDF')} ↗</a></>:<p role="status">{t('Loading original page…','正在加载原题…')}</p>}</dialog>
 </main>;
}
