'use client';
import {useState} from 'react';
import {randomPaper} from '@/lib/random-paper';
import type {Question} from '@/lib/question-bank';

export function RandomPaper({questions,zh,year,unit,onSelect}:{questions:Question[];zh:boolean;year:string;unit:string;onSelect:(ids:string[])=>void}){
 const [mode,setMode]=useState<'marks'|'minutes'>('marks'),[target,setTarget]=useState('30'),[pace,setPace]=useState('1.5'),[topics,setTopics]=useState<string[]>([]),[query,setQuery]=useState(''),[notice,setNotice]=useState('');
 const t=(en:string,cn:string)=>zh?cn:en;
 const available=[...new Set(questions.filter(q=>q.is_leaf&&(!year||String(q.year)===year)&&(!unit||String(q.unit)===unit)).flatMap(q=>q.topics))].sort();
 const shown=available.filter(x=>x.toLowerCase().includes(query.toLowerCase()));
 function generate(){try{const result=randomPaper(questions,{target:Number(target),mode,minutesPerMark:Number(pace),topics,year,unit});onSelect(result.ids);setNotice(zh?`已选 ${result.marks} 分，预计 ${result.minutes} 分钟。${result.exact?'':'已尽量接近目标，可放宽筛选再试。'}`:`Selected ${result.marks} marks, about ${result.minutes} minutes.${result.exact?'':' Closest available within the target; broaden filters to try again.'}`);}catch(e){setNotice(zh?(e as Error).message:'No suitable selection. Increase the target or broaden the filters.');}}
 return <details className="qb-random"><summary>{t('Random practice','随机组卷')}</summary><div className="qb-random-controls"><label>{t('Target','目标')}<select value={mode} onChange={e=>setMode(e.target.value as 'marks'|'minutes')}><option value="marks">{t('Marks','分数')}</option><option value="minutes">{t('Minutes','时间（分钟）')}</option></select></label><label>{t('Amount','数值')}<input type="number" min="1" max="600" value={target} onChange={e=>setTarget(e.target.value)}/></label><label>{t('Minutes per mark (estimate)','每分预计用时（分钟）')}<input type="number" min="0.25" max="10" step="0.25" value={pace} onChange={e=>setPace(e.target.value)}/></label></div><details className="qb-topic-picker"><summary>{t('Limit topics','限定知识点')} · {topics.length||t('Any','不限')}</summary><input aria-label={t('Find topics','查找知识点')} placeholder={t('Find topics','查找知识点')} value={query} onChange={e=>setQuery(e.target.value)}/><div className="qb-topic-options">{shown.map(topic=><label key={topic}><input type="checkbox" checked={topics.includes(topic)} onChange={e=>setTopics(e.target.checked?[...topics,topic]:topics.filter(x=>x!==topic))}/><span>{topic}</span></label>)}</div><button onClick={()=>setTopics([])}>{t('Clear topics','清除知识点')}</button></details><p className="qb-random-note">{t('Uses the current year and paper filters. Any checked topic may appear. Required questions stay together.','沿用当前年份和卷型筛选；勾选多个知识点时，符合任意一个即可。关联题会一起加入。')}</p><button className="qb-primary" onClick={generate} disabled={!questions.length}>{t('Generate · replace selection','随机生成 · 替换当前选题')}</button><p role="status">{notice}</p></details>;
}
