'use client';
import { useEffect, useRef, useState } from 'react';
import { FileText, Check, Layers3, Search, RotateCcw } from 'lucide-react';
import { Copy, useSite } from './site-context';
import { t } from '@/lib/bilingual';
const stages=[t('Organise source material','整理资料'),t('Draft the argument','组织论点'),t('Build the slide','制作页面'),t('Check claims and layout','核对内容与版式')];
export function SlideWorkbench(){
 const {motionPaused}=useSite();const [tick,setTick]=useState(0);const host=useRef<HTMLDivElement>(null);const [visible,setVisible]=useState(false);
 useEffect(()=>{const o=new IntersectionObserver(e=>setVisible(e[0].isIntersecting),{threshold:.12});if(host.current)o.observe(host.current);return()=>o.disconnect();},[]);
 useEffect(()=>{if(motionPaused||!visible)return;const id=setInterval(()=>{if(!document.hidden)setTick(t=>(t+1)%24);},650);return()=>clearInterval(id);},[motionPaused,visible]);
 const stage=motionPaused?3:Math.min(3,Math.floor(tick/5));
 return <section ref={host} className="slide-workbench" id="slide-workbench" data-stage={stage}><div className="workbench-toolbar"><div><p className="eyebrow"><Copy>{t('From evidence to a presentation','从证据到演示文稿')}</Copy></p><h3><Copy>{t('A presentation takes shape.','一页分析怎样形成。')}</Copy></h3></div><button onClick={()=>setTick(0)} aria-label="Replay presentation workflow"><RotateCcw size={18}/></button></div><div className="slide-studio"><aside className="studio-sources"><span className="visual-kicker"><Copy>{t('Research inputs','研究资料')}</Copy></span>{[t('Interview themes','访谈主题'),t('Evidence questions','证据问题'),t('Patient journey','患者路径')].map((v,i)=><div key={i}><FileText size={17}/><Copy>{v}</Copy><Check size={14}/></div>)}<p><Copy>{t('Question → claim → supporting source','问题 → 论点 → 支持来源')}</Copy></p></aside><div className="slide-preview"><span className="slide-page-number">01 / 04</span><p className="slide-overline">RESEARCH SYNTHESIS</p><h4><Copy>{t('What changes a clinical decision?','什么会改变临床判断？')}</Copy></h4><div className={`slide-content ${stage>=1?'shown':''}`}><div className="slide-thesis"><Copy>{t('Read benefit, safety and patient context together.','结合获益、安全性与患者背景理解判断。')}</Copy></div><div className={`slide-columns ${stage>=2?'shown':''}`}>{[t('Event history','事件史'),t('Risk balance','风险权衡'),t('Continuity of care','持续管理')].map((v,i)=><div key={i}><b>0{i+1}</b><Copy>{v}</Copy><i/><i/></div>)}</div></div><div className={`slide-source-line ${stage>=3?'shown':''}`}><Check size={13}/><Copy>{t('Source checked · scope stated · layout reviewed','来源已核对 · 范围已说明 · 版式已审阅')}</Copy></div></div><aside className="studio-stages">{stages.map((v,i)=>{const Icon=[Search,FileText,Layers3,Check][i];return <div className={stage===i?'active':stage>i?'done':''} key={i}><Icon size={17}/><Copy>{v}</Copy></div>})}</aside></div><p className="small muted"><Copy>{t('Illustrative reconstruction of the production workflow, using generalised content rather than a client slide.','用概括性内容重现制作过程，画面不是客户原始幻灯片。')}</Copy></p></section>;
}
