'use client';
import { YiduAnalysisVisual } from './yidu-analysis-visuals';
import { ProjectJourney, JourneyFlow, type JourneyStep } from './project-journey';
import { t } from '@/lib/bilingual';
const steps:JourneyStep[] = [
{id:"research-brief",label:t("Define the question","界定问题"),title:t("What would clinicians need to make a decision?","医生需要哪些信息，才能作出判断？"),method:t("I organised the research around patient groups, treatment decisions and follow-up. This gave the interview synthesis a common set of questions, from unmet needs to the evidence needed for a new treatment approach.","我围绕患者人群、治疗决策和随访安排组织研究问题，以此整理访谈：现有需求在哪里，医生如何权衡，以及新的治疗思路还需要哪些证据。"),result:t("The analysis needed to connect clinical evidence with the circumstances in which a clinician would use it.","分析需要把临床证据，与医生实际作出判断的场景联系起来。"),next:t("Next: organise the interview material so that each conclusion can be traced back to its basis.","下一步：整理访谈材料，让每项判断都能找到依据。")},
{id:"interview-synthesis",label:t("Organise interviews","整理访谈"),title:t("Separate what was said from what it might imply.","先分清原话、归纳和推断。"),method:t("I compared interview material by topic: patient characteristics, current practice, perceived benefit, concerns and operational barriers. The synthesis kept individual experience separate from broader evidence needs.","我按患者特征、当前做法、获益感知、顾虑和执行障碍比较访谈内容，并区分个别医生的经验与仍需进一步验证的问题。"),result:t("A recurring concern can guide the next research question; it does not establish a clinical outcome or a population estimate.","反复出现的顾虑可以提示下一步研究方向，但不能据此认定临床疗效，也不能直接推算总体比例。"),next:t("Next: use the recurring decision factors to build patient profiles.","下一步：将反复出现的决策因素整理成患者画像。")},
{id:"patient-profiles",label:t("Patient profiles","患者画像"),title:t("Give overlapping patient features a clear structure.","让相互重叠的患者特征有清楚的层次。"),method:t("I helped structure profiles around disease mechanism, event history, progression and competing risks. The task was to explain how these features shaped the research questions, while avoiding duplicate categories for the same case.","我围绕疾病机制、事件史、病情进展和风险权衡整理患者画像，说明这些特征怎样影响研究问题，同时避免同一个案因具备多项特征而被重复归类。"),result:t("A useful profile explains the reason for a distinction, rather than accumulating more labels.","有用的患者画像，需要说明为什么这样区分，而不只是增加标签。"),next:t("Next: place these profiles within the patient journey and identify decision points.","下一步：把患者画像放回诊疗过程，找出实际的决策节点。")},
{id:"decision-pathway",label:t("Decision points","决策节点"),title:t("Follow the decision from hospital to outpatient care.","沿住院到门诊的过程，梳理决策。"),method:t("I translated the interview synthesis into pathway diagrams: assessment, the information that changes a decision, reasons for reassessment and the handover to outpatient care. These diagrams organised reported practice for discussion.","我把访谈归纳转化为路径图，依次呈现评估、影响判断的信息、需要复评的原因，以及门诊如何承接住院安排。路径图用于整理受访者描述的做法，支持后续讨论。"),result:t("The same patient label can lead to different decisions when the setting, available information or follow-up arrangements change.","即使患者标签相同，诊疗场景、已有信息和随访安排不同，也可能影响医生的判断。"),next:t("Next: turn the unresolved questions at each decision point into a focused evidence agenda.","下一步：将决策节点上的未解问题，转化为需要补充的证据。")},
{id:"evidence-questions",label:t("Evidence questions","证据问题"),title:t("Make each question specific enough to answer.","把问题细化到可以回答。"),method:t("I grouped clinicians’ questions into efficacy, safety, patient selection and use in practice, then organised FAQ material around the evidence each question required. Questions without a sufficient basis remained open.","我把医生的问题归入疗效、安全性、患者选择和实际使用等主题，再据此整理 FAQ，明确每个问题需要什么证据。依据不足的问题保留为待回答项。"),result:t("The output was a clearer set of evidence and communication needs, with the limits of the available material kept visible.","产出是一组更明确的证据与沟通需求，同时保留现有材料的局限。"),next:t("Next: examine the follow-up workflow needed to support ongoing care.","下一步：检查持续管理所依赖的随访流程。")},
{id:"follow-up-design",label:t("Follow-up needs","随访需求"),title:t("Connect contact, records and the response to a problem.","把联系患者、保存记录和处理问题接起来。"),method:t("I compared the follow-up approaches described in interviews, including digital platforms and staff-led contact. I organised improvement opportunities around planning, reminders, information collection and escalation to a clinician.","我比较访谈中提到的数字平台和人工随访方式，将改进方向整理为制定计划、发送提醒、归集资料，以及把需要处理的问题转交医生。"),result:t("Contacting a patient is one part of follow-up. A workable process also needs accessible records, clear responsibilities and a route for resolving issues.","联系到患者只是随访的一环。完整流程还需要可调取的记录、明确的责任分工，以及发现问题后的处理路径。"),next:t("Further work: test the proposed workflow with the people who would use it, including the burden of recording and handover.","后续方向：由实际使用者检验这些流程建议，重点确认记录和交接是否增加额外负担。")}
];
const visuals=[
<JourneyFlow key="0" kicker={t('Analysis structure','分析结构')} nodes={[[t("Research brief","研究提纲"),t("What needs explaining?","需要解释什么？")],[t("Clinical context","临床场景"),t("Where does the question arise?","问题出现在哪里？")],[t("Evidence needs","证据需求"),t("What would resolve it?","需要什么依据？")]]} />,
<JourneyFlow key="1" kicker={t('Analysis structure','分析结构')} nodes={[[t("Source statement","访谈原话"),t("Keep its context","保留语境")],[t("Topic synthesis","主题归纳"),t("Compare the reasoning","比较判断依据")],[t("Open question","待解问题"),t("Identify the evidence gap","识别证据缺口")]]} />,
<JourneyFlow key="2" kicker={t('Analysis structure','分析结构')} nodes={[[t("Mechanism","疾病机制"),t("Define the starting point","明确分析入口")],[t("Event history","事件史"),t("Find the key distinction","找出关键区别")],[t("Risk context","风险背景"),t("Explain the trade-off","说明权衡因素")]]} />,
<JourneyFlow key="3" kicker={t('Analysis structure','分析结构')} nodes={[[t("Hospital assessment","住院评估"),t("Information available","已有信息")],[t("Reassessment","重新评估"),t("What changes the decision","什么会改变判断")],[t("Outpatient handover","门诊承接"),t("Continuity and responsibility","延续安排与责任")]]} note={t('A map of the research questions; treatment decisions require clinical judgement.','此图呈现研究问题的组织方式；具体诊疗决策须由医生判断。')}/>,
<JourneyFlow key="4" kicker={t('Analysis structure','分析结构')} nodes={[[t("Clinician question","医生问题"),t("Make the concern explicit","说清具体顾虑")],[t("Evidence check","核对依据"),t("What can be answered","哪些已有答案")],[t("Focused FAQ","问题与回答"),t("State what remains open","标明待补证据")]]} />,
<JourneyFlow key="5" kicker={t('Analysis structure','分析结构')} nodes={[[t("Plan & remind","计划与提醒"),t("Assign the next contact","安排下次联系")],[t("Collect & review","归集与核查"),t("Make records accessible","让记录可调取")],[t("Escalate & resolve","转交与处理"),t("A clinician handles concerns","由医生处理问题")]]} />
];
export function YiduJourney(){return <ProjectJourney steps={steps} visuals={visuals.map((visual,i)=>i===0?visual:<YiduAnalysisVisual key={i} step={i}/>)} eyebrow={t('My analysis process','我的分析过程')} title={t('From interviews to a clearer pathway.','从访谈到决策与随访。')}/>;}
