'use client';
import { Check, FileText, CalendarDays, Stethoscope } from 'lucide-react';
import { Copy } from './site-context';
import { t } from '@/lib/bilingual';
export function YiduAnalysisVisual({step}:{step:number}){
 if(step===1)return <div className="journey-visual insight-notes"><span className="visual-kicker"><Copy>{t('Keep three levels distinct','分清三个层次')}</Copy></span>{[[t('Source context','材料语境'),t('Who raised the issue, and in which setting?','谁提出的问题，出现在什么场景？')],[t('Theme','归纳主题'),t('Benefit, safety or practical barriers','获益、安全性或执行障碍')],[t('Interpretation','分析判断'),t('What evidence would resolve the concern?','还需什么证据回答这一顾虑？')]].map(([a,b],i)=><div className={`insight-note note-${i}`} key={i}><FileText size={18}/><strong><Copy>{a}</Copy></strong><p><Copy>{b}</Copy></p></div>)}</div>;
 if(step===2)return <div className="journey-visual profile-visual"><span className="visual-kicker"><Copy>{t('A hierarchy for the research questions','研究问题的分层方式')}</Copy></span><div className="profile-root"><Stethoscope size={25}/><strong><Copy>{t('Post-stroke prevention','卒中后预防')}</Copy></strong></div><div className="profile-branches">{[[t('Event history','事件史'),t('Prior and recurrent events','既往与复发事件')],[t('Mechanism','疾病机制'),t('Why did the event occur?','事件为何发生？')],[t('Risk context','风险背景'),t('Ischaemic and bleeding concerns','缺血与出血顾虑')]].map(([a,b],i)=><div key={i}><strong><Copy>{a}</Copy></strong><span><Copy>{b}</Copy></span></div>)}</div><p className="visual-note"><Copy>{t('Analytical dimensions may overlap; they are not a treatment algorithm.','分析维度可能重叠；此图不是治疗选择算法。')}</Copy></p></div>;
 if(step===3)return <div className="journey-visual care-timeline"><span className="visual-kicker"><Copy>{t('Where a decision is revisited','判断在哪些节点重新被检视')}</Copy></span>{[[t('Hospital','住院阶段'),t('Assessment and available evidence','评估与已有证据')],[t('Discharge','出院衔接'),t('Plan, responsibility and records','计划、责任与记录')],[t('Follow-up','后续复评'),t('New events, concerns or missing information','新事件、顾虑或信息缺口')]].map(([a,b],i)=><div key={i}><span>0{i+1}</span><div><strong><Copy>{a}</Copy></strong><p><Copy>{b}</Copy></p></div></div>)}</div>;
 if(step===4)return <div className="journey-visual faq-board"><span className="visual-kicker"><Copy>{t('Build an evidence-led FAQ','按证据组织 FAQ')}</Copy></span>{[t('Which patients were studied?','研究纳入了哪些患者？'),t('Which outcomes support the benefit?','获益依据来自哪些终点？'),t('How was safety assessed?','安全性怎样评估？')].map((q,i)=><div key={i}><span>Q{i+1}</span><strong><Copy>{q}</Copy></strong><div><Check size={13}/><Copy>{t('Match each answer to its evidence','每项回答对应支持证据')}</Copy></div></div>)}</div>;
 if(step===5)return <div className="journey-visual followup-board"><span className="visual-kicker"><Copy>{t('A workable follow-up record','可执行的随访记录')}</Copy></span><CalendarDays size={32}/><div className="followup-status">{[t('Next contact planned','下次联系已安排'),t('Information recorded','信息可调取'),t('Responsibility assigned','处理责任已明确')].map((x,i)=><div key={i}><span className={`status-check status-${i}`}><Check size={14}/></span><Copy>{x}</Copy></div>)}</div><p className="visual-note"><Copy>{t('Workflow illustration, not a patient record. Clinical concerns are passed to a clinician.','流程示意，并非患者记录；临床问题交由医生处理。')}</Copy></p></div>;
 return null;
}
