import { Copy, SiteLink } from '@/components/site-context';
import { CaseShell } from '@/components/case-shell';
import { McrExplorer } from '@/components/mcr-explorer';
export const metadata = { title: 'Colistin adjuvants | Bill Huang', description: 'Exploratory checkerboard growth records and membrane assay development in an MCR-1 research project.', alternates: { canonical: 'https://betoadfish.github.io/projects/mcr1-colistin', languages: { en: 'https://betoadfish.github.io/projects/mcr1-colistin', 'zh-CN': 'https://betoadfish.github.io/zh/projects/mcr1-colistin' } } };
export default function MCR() {
    return <CaseShell theme="mcr" title="Colistin adjuvants" subtitle="Interpreting combination effects and membrane assays." role="Research intern" date="July - September 2025" institution="Bio21 Institute, University of Melbourne" summary="I investigated natural compounds as potential colistin adjuvants in a project on MCR-1-mediated resistance. My work connected growth-inhibition screening with the development of membrane-permeability assays.">
 <section className="editorial-section editorial-grid"><div><p className="eyebrow"><Copy>{"The research question"}</Copy></p><h2><Copy>{"What explains a combination effect?"}</Copy></h2></div><div><p><Copy>{"The project examined honokiol, pterostilbene and osthol alongside colistin. MIC and checkerboard experiments helped identify combinations for further study. PI and NPN assays were then used to investigate membrane-related explanations."}</Copy></p><p><Copy>{"A growth readout can identify a response under a defined condition. It cannot, by itself, establish direct inhibition of the resistance protein. That distinction shaped the next stage of the work."}</Copy></p></div></section>
 <McrExplorer />
 <section className="editorial-section"><p className="eyebrow"><Copy>{"Assay development"}</Copy></p><h2><Copy>{"Investigating the source of the signal."}</Copy></h2><div className="practice-grid"><Copy>{[
        ['Growth inhibition', 'MIC and checkerboard work established a screening workflow. Differences between plates and non-monotonic wells require review before assigning a formal synergy estimate.'],
        ['Membrane assays', 'The project records document questions about reagent freshness, concentration, spectral overlap, growth phase and OD normalisation in PI/NPN measurements.'],
        ['Mechanistic interpretation', 'The next experiments need to separate fluorescence background and membrane effects from a specific molecular target. The available records leave that mechanism unresolved.']
    ].map(([t, b]) => <article key={t}><h3><Copy>{t}</Copy></h3><p><Copy>{b}</Copy></p></article>)}</Copy></div></section>
 <section className="editorial-section editorial-grid"><div><p className="eyebrow"><Copy>{"My contribution"}</Copy></p><h2><Copy>{"Connecting screening"}</Copy><br /><Copy>{"with assay development."}</Copy></h2></div><div><p><Copy>{"I conducted MIC and checkerboard work, analysed experimental readouts and refined the membrane assay workflow. I used the initial screen to guide further investigation while checking how the measurement itself could affect the interpretation."}</Copy></p><p><Copy>{"The next analytical step is to reconcile plate layouts, replicate structure and endpoint rules. A mechanistic conclusion would also need controls that distinguish an effect on the membrane from direct action on the resistance protein."}</Copy></p></div></section>
 <details className="source-disclosure"><summary><Copy>{"Sources and scope"}</Copy></summary><p><Copy>{"End Project Summary, screening and membrane-assay sections; processed checkerboard workbooks dated August 2025; personal research account and CV for role and dates. Experimental records reviewed extend into September 2025."}</Copy></p><p><Copy>{"The source figures label compound concentrations in \u00B5g/mL. This page retains those units and does not reuse an unverified fold-reduction claim. Labels such as BL21(DE3), DH5\u03B1 and pBAD are reproduced as recorded, without assuming expression status."}</Copy></p></details>
 </CaseShell>;
}
