import { t } from './bilingual';
export const journey = [
  {id:'substrate',label:t('Substrate','底物路线'),title:t('Make a six-carbon substrate accessible.','先解决六碳底物从哪里来。'),method:t('HuBP was not available through chemical or enzymatic synthesis. I built the accessible route instead: PHI converts F6P into Hu6P.','项目开始时，HuBP 没有可用的化学或酶法供给路线。我从可获得的 F6P 出发，利用 PHI 制备 Hu6P。'),result:t('A feasible experimental entry point, with the C1 phosphate still missing.','建立了六碳底物的实验入口，但 Hu6P 仍缺少 C1 磷酸。'),next:t('Identify mutations around the phosphate-binding region.','接着考察磷酸结合区域附近的突变。')},
  {id:'structure',label:t('Design','突变设计'),title:t('Change space and polarity near C1.','围绕 C1 端，改变空间与极性。'),method:t('I selected I164T to introduce a hydroxyl group, S368A to remove one, and S368C to alter its interaction chemistry. These positions sit close to the C1 end of RuBP.','我选择 I164T 引入羟基，S368A 去掉羟基，S368C 改变局部相互作用。这些位置靠近 RuBP 的 C1 端，适合检验底物定位与容纳空间。'),result:t('Three focused designs to test longer-sugar recognition.','得到三个可实验检验的局部改造方案。'),next:t('Build a readout that can distinguish activity from background.','为这些设计建立能区分活性与背景的检测体系。')},
  {id:'assay',label:t('Readout','活性检测'),title:t('Turn product formation into a measurable signal.','让产物形成转化为可测信号。'),method:t('I developed a coupled assay linking 3-PG formation to NADH consumption at 340 nm. RuBP established the positive control; supporting-enzyme controls separated substrate routes.','我建立了将 3-PG 生成与 NADH 消耗相连的偶联体系，用 340 nm 吸光度读取信号。先用 RuBP 建立阳性对照，再通过辅助酶对照区分底物路线。'),result:t('A working native-substrate benchmark for the later assays.','获得天然底物的明确响应，建立后续实验的检测基准。'),next:t('Check whether PHI actually supplies the precursor.','下一步先确认 PHI 能否提供前体。')},
  {id:'phi',label:t('PHI / NMR','PHI / NMR'),title:t('Verify precursor formation independently.','用 NMR 单独验证前体转化。'),method:t('I expressed and purified PHI, then followed F6P conversion by ³¹P NMR. The peak assigned to Hu6P increased between 24 and 144 hours.','我表达、纯化 PHI，并用 ³¹P NMR 跟踪 F6P 的转化。归属于 Hu6P 的峰在 24 至 144 小时之间逐渐增加。'),result:t('PHI-mediated precursor conversion was supported; supply was slow.','结果支持 PHI 介导的前体转化，同时提示供给过程较慢。'),next:t('Test the RuBisCO preparations against the native substrate first.','随后先检验 RuBisCO 蛋白制备物的天然底物活性。')},
  {id:'evidence',label:t('Activity','突变体活性'),title:t('Confirm active protein before testing new chemistry.','先确认蛋白有活性，再检验新底物。'),method:t('I expressed and purified WT and three mutants. All three retained measurable RuBP activity. Exploratory monophosphate assays produced no clear alternative-substrate response.','我完成 WT 和三个突变体的表达与纯化，三个突变体都保留了可测的 RuBP 活性。单磷酸底物实验则没有给出明确的替代底物响应。'),result:t('Active preparations established; weak exploratory signals needed resolution.','确认了蛋白制备物仍具活性；微弱的探索信号尚需进一步验证。'),next:t('Return to ligand positioning to decide what to change next.','回到配体定位，寻找下一轮改造的依据。')},
  {id:'docking',label:t('Next design','结构启示'),title:t('Preserve the anchor, then make room.','保留定位作用，再寻找额外空间。'),method:t('I compared native-ligand redocking with HuBP and Hu6P poses in WT and mutant models. Removing a phosphate anchor loosened orientation; I164T suggested a possible new polar contact.','我将天然配体重对接与 WT、突变模型中的 HuBP 和 Hu6P 构象进行比较。缺少磷酸锚定会使方向松动；I164T 则提示了新的潜在极性接触。'),result:t('Prioritise full HuBP supply and mutations that retain productive positioning.','下一步优先获得完整 HuBP，并在保留有效定位的前提下设计突变。'),next:t('Combine matched controls, repeat measurements and independent product identification.','配合匹配对照、重复测量和独立产物鉴定，检验下一轮设计。')},
];
