import { Copy, SiteLink } from '@/components/site-context';
import { CaseShell } from '@/components/case-shell';
import { HubiscoConcept } from '@/components/hubisco-concept';
import { EfficiencyComparison } from '@/components/project-highlights';
import { VinaTerminal } from '@/components/vina-terminal';
import { HubiscoJourney } from '@/components/hubisco-journey';
import { t } from '@/lib/bilingual';
export const metadata={title:'HuBisCO | Bill Huang',description:'Substrate chemistry, enzyme engineering and an experimental route towards benign oxygenation.',alternates:{canonical:'https://betoadfish.github.io/projects/hubisco',languages:{en:'https://betoadfish.github.io/projects/hubisco','zh-CN':'https://betoadfish.github.io/zh/projects/hubisco'}}};
const references=[
  {id:'ref-1',name:'Tcherkez et al., 2006',topic:t('Catalytic constraints','催化约束'),url:'https://doi.org/10.1073/pnas.0600605103'},
  {id:'ref-2',name:'Flamholz et al., 2019',topic:t('Revisiting kinetic trade-offs','重新检验动力学 trade-off'),url:'https://doi.org/10.1021/acs.biochem.9b00237'},
  {id:'ref-3',name:'Prywes et al., 2023',topic:t('Function, evolution and engineering','功能、演化与酶工程'),url:'https://doi.org/10.1146/annurev-biochem-040320-101244'},
  {id:'ref-4',name:'Andersson, 2008',topic:t('Catalysis and active-site regulation','催化与活性位点调控'),url:'https://doi.org/10.1093/jxb/ern091'},
];
function Cite({ids}:{ids:number[]}){return <sup className="paper-cite">{ids.map((n,i)=><span key={n}>{i>0?', ':''}<a href={`#ref-${n}`} aria-label={`Reference ${n}`}>{n}</a></span>)}</sup>;}
export default function HubiscoPage(){
  return <CaseShell theme="hubisco" title="HuBisCO" subtitle={t('Reimagining RuBisCO through substrate chemistry.','换一种底物，探索固碳的新路线。')} role={t('Biochemistry research project','生物化学研究项目')} date={t('2026 · Jan–May','2026 年 1–5 月')} institution={t('University of Cambridge · Prywes Lab','剑桥大学 · Prywes 实验室')} summary={t('I developed the protein and assay workflows for an alternative-substrate project, verified native mutant activity and precursor conversion, and used structural analysis to guide the next design.','我为替代底物研究建立蛋白与检测流程，验证突变体的天然底物活性和前体转化，再用结构分析确定下一步设计。')}>
    <section className="project-intro hubisco-intro" id="intro"><p className="eyebrow"><Copy>{t('The question behind the project','项目的出发点')}</Copy></p><h2><Copy>{t('When tuning the enzyme is not enough.','当常规酶优化面临约束。')}</Copy></h2><p className="intro-lead"><Copy>{t('RuBisCO fixes CO₂, but its competing reaction with O₂ produces 2-phosphoglycolate and a costly recycling pathway. Decades of engineering have had to contend with a catalytic mechanism whose speed, substrate affinity and gas discrimination are interrelated.','RuBisCO 固定 CO₂，却也会与 O₂ 反应，生成 2-磷酸乙醇酸，并引出耗能的光呼吸回收过程。多年的酶工程研究始终需要面对一个问题：催化速率、底物亲和力与气体选择性，并不是可以独立调高的参数。')}</Copy><Cite ids={[1,2,3]}/></p>
      <div className="intro-grid">
        <article><span>01</span><h3><Copy>{t('A constrained starting point','传统改造的瓶颈')}</Copy></h3><p><Copy>{t('Catalytic trade-offs can make faster carboxylation difficult to separate from oxygenation. Their exact limits remain under investigation, but they motivate strategies beyond optimising the same reaction.','催化机制中的 trade-off，使提高羧化效率与降低光呼吸损耗难以完全分开。约束的具体边界仍在研究中，也因此值得探索优化原有反应之外的路线。')}</Copy><Cite ids={[1,2]}/></p></article>
        <article><span>02</span><h3><Copy>{t('Make oxygenation useful','降低光呼吸的代谢代价')}</Copy></h3><p><Copy>{t('HuBisCO asks whether changing the sugar substrate could change the products: an oxygenation reaction that yields usable carbon instead of 2-phosphoglycolate.','HuBisCO 尝试改变糖底物，从而改变产物组成：让加氧反应生成可继续利用的碳产物，避免生成 2-磷酸乙醇酸。')}</Copy></p></article>
        <article><span>03</span><h3><Copy>{t('Why HuBP?','为什么是 HuBP？')}</Copy></h3><p><Copy>{t('Hexulose-1,6-bisphosphate adds one carbon to the five-carbon RuBP framework and retains both phosphates. The proposed oxygenation then yields two 3-PG molecules. The phosphates also matter for positioning the sugar in the active site.','己酮糖-1,6-二磷酸比五碳 RuBP 多一个碳，并保留两个磷酸基团。设想中的加氧产物因此变为两分子 3-PG；两个磷酸基团也参与糖在活性位点中的定位。')}</Copy><Cite ids={[4]}/></p></article>
        <article><span>04</span><h3><Copy>{t('My experimental entry point','我的实验切入点')}</Copy></h3><p><Copy>{t('Could RuBisCO accommodate a hexulose substrate, and could local mutations help? With HuBP unavailable, I used Hu6P to begin testing the six-carbon backbone and identify what the next design would need.','RuBisCO 能否容纳己酮糖底物，局部突变能否提供帮助？在 HuBP 无法获得的情况下，我从 Hu6P 开始检验六碳骨架，并寻找下一轮设计需要解决的问题。')}</Copy></p></article>
      </div>
      <div className="reference-strip" aria-label="Research references">{references.map((ref,i)=><SiteLink key={ref.id} id={ref.id} href={ref.url} target="_blank" rel="noreferrer"><span>{i+1}</span><b>{ref.name}</b><small><Copy>{ref.topic}</Copy></small></SiteLink>)}</div>
      <EfficiencyComparison/><HubiscoConcept/>
    </section>
    <section className="featured-workbench" id="docking-workbench"><p className="eyebrow"><Copy>{t("A closer look / recorded docking workflow","直观了解 / 已记录的分子对接流程")}</Copy></p><VinaTerminal/></section><HubiscoJourney/>
    <section className="editorial-section solved-insight"><article><p className="eyebrow"><Copy>{t("Problem addressed","解决了什么问题")}</Copy></p><h3><Copy>{t("Make an inaccessible-substrate question experimentally tractable.","把底物难以获得的设想，拆成可检验的问题。")}</Copy></h3><p><Copy>{t("I established protein preparations, native-substrate controls and a PHI–NMR route to assess precursor supply. These separated protein inactivity from substrate-access and detection limitations.","我建立蛋白制备、天然底物对照和 PHI–NMR 前体检测路线，逐步区分蛋白失活、底物供给和检测能力的限制。")}</Copy></p></article><article><p className="eyebrow"><Copy>{t("Design insight","得到什么启示")}</Copy></p><h3><Copy>{t("Secure the substrate and its positioning together.","底物供给与活性位点定位，需要一起解决。")}</Copy></h3><p><Copy>{t("Native mutant activity and slow precursor conversion were observed; alternative-substrate turnover was not established. The next design should prioritise authentic HuBP, phosphate anchoring and direct product detection.","实验观察到突变体天然底物活性和缓慢的前体转化，但尚未确立替代底物催化。下一轮设计应优先获得真实 HuBP，关注磷酸基团定位，并直接检测产物。")}</Copy></p></article></section><section className="editorial-section contribution-section"><div><p className="eyebrow"><Copy>{t('Prywes Lab / Cambridge','Prywes 实验室 / 剑桥')}</Copy></p><h2><Copy>{t('Building the experiment in a new laboratory.','在新实验室中，把实验体系建立起来。')}</Copy></h2></div><div><p><Copy>{t('I joined Noam Prywes as he established his Cambridge laboratory and helped put protein expression, purification and activity-assay workflows in place. This project connected substrate supply, protein biochemistry, NMR and structural reasoning within one experimental route.','在 Noam Prywes 博士组建剑桥实验室时，我参与了实验室搭建，并建立蛋白表达、纯化与活性检测流程。这个项目把底物供给、蛋白生化、NMR 和结构分析连接成了一条实验路线。')}</Copy></p><p><Copy>{t('Working with Dr Prywes and with NMR support from Dr David Russell, I learned to use each result to sharpen the next experiment: secure the right substrate, preserve its positioning and test product formation directly.','在 Prywes 博士的指导及 David Russell 博士的 NMR 支持下，我逐步明确了下一步工作的重点：获得正确底物、保留有效定位，再直接检验产物形成。')}</Copy></p><SiteLink className="text-link" href="https://pryweslab.org/" target="_blank" rel="noreferrer"><Copy>{t('Prywes Lab ↗','Prywes 实验室 ↗')}</Copy></SiteLink></div></section>
  </CaseShell>;
}
