import type { Metadata } from 'next';
import { CaseShell } from '@/components/case-shell';
import { StructureViewer } from '@/components/structure-viewer';
import { SourceFigure } from '@/components/source-figure';
import { NmrChart, ConcentrationChart } from '@/components/evidence-charts';
export const dynamic = 'force-static';
export const metadata: Metadata = { title: 'HuBisCO | Bill Huang', description: 'RuBisCO substrate research, experimental decisions and selected structural and biochemical evidence.' };
export default function HuBisCO(){return <CaseShell theme="hubisco" title="HuBisCO" subtitle="Testing alternative substrate chemistry in RuBisCO." role="Biochemistry research project" date="2026" institution="Prywes Lab, University of Cambridge" summary="I investigated how local active-site interactions might affect the accommodation of an alternative sugar-phosphate substrate. The work combined recombinant proteins, coupled assays, phosphorus-31 NMR and structural analysis.">
  <nav className="case-local-nav" aria-label="HuBisCO sections"><a href="#overview">Overview</a><a href="#question">Research decisions</a><a href="#structure">Structure</a><a href="#evidence">Evidence</a><a href="#contribution">Contribution</a><a href="#sources">Sources</a></nav>
  <section className="editorial-section" id="overview"><div className="result-banner"><p className="eyebrow">Project result</p><h2>Alternative-substrate turnover was not established.</h2><p>The study produced experimental tools and candidate structural explanations. HuBP was not available, and the exploratory mutant signals did not support a claim of improved activity.</p></div></section>
  <section className="editorial-section" id="question"><p className="eyebrow">Research decisions</p><h2>Three choices that shaped the study.</h2><div className="decision-path">
    <details className="decision-step" open><summary><span>01</span><h3>Choose local interactions to test</h3><p>Use the deposited structure to narrow the mutation design.</p></summary><p>I164 and S368 sit near the C1-phosphate region of bound RuBP. I164T changes steric bulk and polarity; S368A removes the hydroxyl group, while S368C changes its chemistry. These substitutions tested plausible local constraints rather than predicting an activity gain.</p></details>
    <details className="decision-step"><summary><span>02</span><h3>Adapt when HuBP was unavailable</h3><p>Establish an accessible experimental route and define its scope.</p></summary><p>The intended substrate was HuBP. With no practical supply during the project, exploratory assays used Hu6P and Ru5P conditions. PHI-mediated precursor conversion was examined by NMR. These experiments could assess parts of the system, but could not directly establish HuBP turnover.</p></details>
    <details className="decision-step"><summary><span>03</span><h3>Reassess weak signals</h3><p>Return to the structure without treating docking as catalytic evidence.</p></summary><p>When the assays gave no clear alternative-substrate activity, I revisited docking and active-site geometry to guide follow-up hypotheses. The mutant assays lacked repeated measurements; background, supporting enzymes and product identity remained unresolved.</p></details>
  </div></section>
  <section className="editorial-section" id="structure"><p className="eyebrow">Structural rationale</p><h2>Explore the reference active site.</h2><p>Select a residue to inspect its environment and the hypothesis it informed. Both deposited models are wild-type references. The bound ligand in 9RUB is RuBP.</p><StructureViewer/></section>
  <section className="editorial-section" id="evidence"><p className="eyebrow">Selected experimental records</p><h2>Read the evidence behind the account.</h2>
    <SourceFigure src="/evidence/hubisco/purification.webp" title="Protein preparations" caption="SDS-PAGE panels showing the WT purification workflow and retained WT, mutant and PHI preparations. The original lane and molecular-weight labels are preserved." source="Project dissertation, page 11, Figure 4a and 4b; purification discussion on page 12." notes="Less S368C sample was loaded. Band intensity therefore cannot be compared directly as a measure of yield. The dissertation notes residual bands around 26 kDa in I164T and S368C. These images document recovered protein; activity needs a separate measurement."/>
    <SourceFigure src="/evidence/hubisco/native-assay.webp" title="A native-substrate benchmark and supporting-enzyme controls" caption="The retained project figure compares a RuBP-positive condition with PRK and PHI assay conditions. The arrow marks substrate addition after the initial stabilisation period." source="Project figure WT Assay.svg; dissertation, WT assays on Ru5P and F6P." notes="PRK and PHI labels describe inclusion or omission of supporting enzymes. The displayed NADH scale and rate annotations are inherited from the original processed figure, not newly fitted for this website. These traces support an operational native-substrate response; the figure's fitted-rate labels should not be read as validated mechanistic parameters."/>
    <SourceFigure src="/evidence/hubisco/nmr.webp" title="PHI precursor chemistry by phosphorus-31 NMR" caption="Stacked spectra at 0 hours (red), 24 hours (green) and 144 hours (blue). The source assigns the rising peak near 4.25 ppm to Hu6P and the larger peak near 3.75 ppm to F6P." source="Project spectrum Bill NMR 0-144 hrs.svg; dissertation, PHI activity characterisation." notes="The spectra follow PHI-mediated precursor chemistry. They do not directly measure RuBisCO turnover. Hu6P is the source's peak assignment; independent product confirmation would strengthen it."/>
    <NmrChart/>
  </section>
  <section className="editorial-section editorial-grid" id="contribution"><div><p className="eyebrow">Contribution and collaboration</p><h2>Experimental work<br/>and structural interpretation.</h2></div><div><p>I worked on WT and mutant protein expression and purification, YckF/PHI preparation, coupled NADH assay development, and the analysis of structural and experimental results. My research account describes shifting part of the work towards docking when the assays remained inconclusive.</p><p>Dr Noam Prywes supervised the project. The dissertation acknowledges NMR assistance from Dr David Russell. The retained records do not assign every NMR acquisition or processing step to an individual, so I describe my contribution as preparation and interpretation within the project rather than sole acquisition.</p></div></section>
  <section className="editorial-section editorial-grid" id="next-steps"><div><p className="eyebrow">Next experiments</p><h2>Resolve substrate access<br/>and assay attribution.</h2></div><div><p>A direct test needs verified HuBP, matched WT and mutant inputs, repeated measurements and controls for supporting enzymes. An independent product assay would help distinguish conversion from background.</p><p>A denser NMR time course would also clarify precursor availability. Total protein concentration alone cannot establish how much active enzyme enters a comparison.</p></div></section>
  <section id="sources" className="source-disclosure"><h3>Sources and downloads</h3><p>The account follows the project dissertation and laboratory records. Personal training notes clarify the work described, but do not override the experimental results.</p><details><summary>Additional reported preparation values</summary><p>These values were supplied in the original portfolio brief. Their exact preparation records have not been reconciled, so they are retained as supplementary material rather than headline findings.</p><ConcentrationChart/></details><p className="small muted">Reaction-rate estimates require reconciliation with the retained worksheet before they can support a quantitative comparison.</p><div className="actions"><a className="button primary" href="/downloads/HuBisCO-project-brief.pdf" download>Download project brief (PDF) ↓</a><a className="text-link" href="/projects">Other research ↗</a></div></section>
  </CaseShell>;}
