import { Copy, SiteLink } from '@/components/site-context';
import { CaseShell } from '@/components/case-shell';
import { ProjectIntro } from '@/components/project-intro';
import { StructureViewer } from '@/components/structure-viewer';
import { SourceFigure } from '@/components/source-figure';
import { NmrChart } from '@/components/evidence-charts';
import { MutantAssays, DockingRecords } from '@/components/hubisco-evidence';
import { t, type CopyText } from '@/lib/bilingual';
export const dynamic = 'force-static';
export const metadata = { title: 'HuBisCO | Bill Huang', description: 'Building and testing a RuBisCO engineering system: substrate access, mutant activity, PHI NMR and docking insights.', alternates: { canonical: 'https://betoadfish.github.io/projects/hubisco', languages: { en: 'https://betoadfish.github.io/projects/hubisco', 'zh-CN': 'https://betoadfish.github.io/zh/projects/hubisco' } } };
function Chapter({ number, title, body }: {number:string;title:CopyText;body:CopyText}) { return <div className="chapter-heading"><p className="eyebrow"><Copy>{t(`Research sequence / ${number}`, `研究主线 / ${number}`)}</Copy></p><h2><Copy>{title}</Copy></h2><p><Copy>{body}</Copy></p></div>; }
export default function HuBisCO() {
 return <CaseShell theme="hubisco" title="HuBisCO" subtitle={t('Reworking the substrate chemistry of RuBisCO.', '从底物化学出发，探索 RuBisCO 的改造路线。')} role={t('Biochemistry research project','生物化学研究项目')} date="2026" institution="Prywes Lab, University of Cambridge" summary={t('I built an experimental system for testing alternative sugar phosphates: purified RuBisCO variants with measurable native activity, characterised PHI-mediated precursor conversion by NMR, and used docking to identify priorities for the next round of enzyme design.', '我围绕替代糖磷酸底物搭建了实验体系：制备 RuBisCO 突变体并确认其天然底物活性，用 NMR 表征 PHI 催化的前体转化，再结合 docking 分析，为下一轮酶设计确定优先方向。')}>
 <ProjectIntro title={t('Why change the substrate, as well as the enzyme?', '为什么改造酶，也要重新选择底物？')} lead={t('RuBisCO sits at the entry point of biological carbon fixation. HuBisCO explores a different way to address its competing reaction with oxygen: change the sugar substrate so that oxygenation could yield useful carbon products.', 'RuBisCO 是生物固碳的关键酶。HuBisCO 项目尝试换一个思路处理它与氧气的副反应：改变糖底物，让加氧反应也有可能生成可利用的碳产物。')} items={[
 {title:t('What does RuBisCO do?', 'RuBisCO 做什么？'),body:t('RuBisCO adds CO₂ to the five-carbon substrate ribulose-1,5-bisphosphate (RuBP), producing two molecules of 3-phosphoglycerate (3-PG). These products enter central carbon metabolism.', 'RuBisCO 将 CO₂ 加到五碳底物核酮糖-1,5-二磷酸（RuBP）上，生成两分子 3-磷酸甘油酸（3-PG），供后续碳代谢利用。')},
 {title:t('Why engineer it?', '为什么要改造 RuBisCO？'),body:t('O₂ competes with CO₂. Oxygenation of RuBP produces one 3-PG and one 2-phosphoglycolate, whose recycling creates a photorespiratory cost. Engineering therefore has to address the chemistry of competing reactions, as well as catalytic performance.', 'O₂ 会与 CO₂ 竞争。RuBP 的加氧反应生成一分子 3-PG 和一分子 2-磷酸乙醇酸，后者需要经过光呼吸途径回收。因此，改造目标既包括酶的催化表现，也包括副反应究竟生成什么。')},
 {title:t('What is the HuBisCO idea?', 'HuBisCO 想改变什么？'),body:t('The project asks whether a RuBisCO scaffold can accommodate a six-carbon sugar. The extra carbon could change the oxygenation products to two 3-PG molecules. This is a proposed reaction design to test, not an established activity of the engineered variants.', '项目考察 RuBisCO 能否容纳六碳糖底物。多出的一个碳，理论上可让加氧反应生成两分子 3-PG。这是需要实验检验的反应设计，本项目尚未证明突变体实现了这一路线。')},
 {title:t('Why HuBP?', '为什么选 HuBP？'),body:t('D-hexulose-1,6-bisphosphate (HuBP) extends the carbon skeleton while retaining two phosphate groups that may help anchor the ligand. The proposed products are two 3-PG molecules after oxygenation, or 3-PG plus 4-phosphoerythronate after carboxylation.', 'D-己酮糖-1,6-二磷酸（HuBP）延长了碳骨架，同时保留两个可能参与底物定位的磷酸基团。设想中的加氧产物为两分子 3-PG；羧化产物则为 3-PG 和 4-磷酸赤藓糖酸。')}
 ]}/>
 <nav className="case-local-nav" aria-label="HuBisCO"><SiteLink href="#substrate"><Copy>{t('01 Substrate','01 底物路线')}</Copy></SiteLink><SiteLink href="#structure"><Copy>{t('02 Mutant design','02 突变设计')}</Copy></SiteLink><SiteLink href="#assay"><Copy>{t('03 Assay','03 活性检测')}</Copy></SiteLink><SiteLink href="#phi"><Copy>{t('04 PHI / NMR','04 PHI / NMR')}</Copy></SiteLink><SiteLink href="#evidence"><Copy>{t('05 Mutant activity','05 突变体活性')}</Copy></SiteLink><SiteLink href="#docking"><Copy>{t('06 Docking','06 Docking')}</Copy></SiteLink></nav>
 <section className="editorial-section" id="substrate"><Chapter number="01" title={t('HuBP was unavailable. Build an accessible precursor route.', 'HuBP 无法获得，先建立可行的前体路线。')} body={t('Neither a practical chemical nor an enzymatic supply of HuBP was available within the project. I therefore worked with phosphohexuloisomerase (PHI/YckF), which converts fructose-6-phosphate (F6P) towards hexulose-6-phosphate (Hu6P, also called H6P in the records). This made six-carbon substrate chemistry experimentally accessible, while leaving the missing C1 phosphate as an important difference.', '项目期间没有可用的化学或酶法途径供给 HuBP。我因此转向磷酸己酮糖异构酶（PHI/YckF），利用它将果糖-6-磷酸（F6P）转化为己酮糖-6-磷酸（Hu6P，原记录也写作 H6P）。这让六碳底物的探索有了实验入口，但 Hu6P 缺少 C1 磷酸，不能视为 HuBP 的等效替代物。')}/>
 <SourceFigure src="/evidence/hubisco/reaction-scheme.svg" title={t('Native and proposed reaction chemistry','天然反应与设想中的替代反应')} caption={t('The project scheme compares the products of native RuBP chemistry with the proposed HuBP reactions. The extra carbon changes the product balance in the design.', '原项目反应图比较天然底物 RuBP 与目标底物 HuBP 的反应产物，说明设计中多出的一个碳如何改变产物组成。')} notes={t('Proposed transformations in this scheme are hypotheses. The scheme itself is not evidence of measured HuBP conversion.', '图中的目标反应属于研究假设，反应示意图本身不代表已经测得 HuBP 转化。')} source={t('Original project reaction scheme; dissertation introduction and assay design.', '来源：原项目反应示意图、论文引言及检测体系设计章节。')}/></section>
 <section className="editorial-section" id="structure"><Chapter number="02" title={t('Test the interactions around the C1 phosphate.', '从 C1 磷酸附近的相互作用选择突变。')} body={t('The Rhodospirillum rubrum Form II RuBisCO structure put I164 and S368 near the C1-phosphate region of RuBP. I chose substitutions that changed space or polarity locally, guided by reported retention of native activity. The aim was to test substrate accommodation while keeping a working catalytic scaffold.', '在深红红螺菌（Rhodospirillum rubrum）的 II 型 RuBisCO 结构中，I164 和 S368 位于 RuBP 的 C1 磷酸附近。我参考已有天然底物活性记录，选择能局部改变空间或极性的替换，希望在保留催化骨架的前提下考察底物容纳方式。')}/>
 <div className="practice-grid">{[
 [t('I164T / Introduce a polar group','I164T / 引入极性基团'),t('A threonine side chain adds a hydroxyl group and slightly changes local space, offering a possible new interaction with the sugar phosphate.', '苏氨酸侧链引入羟基，并略微改变局部空间，可能为糖磷酸提供新的接触方式。')],
 [t('S368A / Remove the hydroxyl','S368A / 去掉羟基'),t('Alanine makes the side chain smaller and removes the serine hydroxyl, testing the contribution of that local constraint.', '丙氨酸缩小侧链并去掉丝氨酸羟基，用于考察这一位置的空间和极性约束。')],
 [t('S368C / Change contact chemistry','S368C / 改变接触性质'),t('Cysteine replaces the hydroxyl with a thiol, changing the hydrogen-bonding chemistry near the phosphate-binding region.', '半胱氨酸用巯基替换羟基，改变磷酸结合区域附近的氢键相互作用性质。')]
 ].map(([title,body],i)=><article key={i}><h3><Copy>{title}</Copy></h3><p><Copy>{body}</Copy></p></article>)}</div><StructureViewer/><p className="small muted"><Copy>{t('The viewer shows deposited wild-type structures, not the constructed mutant models. 9RUB contains bound RuBP.', '浏览器展示的是数据库中的野生型参考结构，并非本项目构建的突变模型；9RUB 中结合的配体为 RuBP。')}</Copy></p></section>
 <section className="editorial-section" id="assay"><Chapter number="03" title={t('Develop a coupled readout, then establish the native control.', '建立偶联检测体系，先确认天然底物的阳性响应。')} body={t('I developed a coupled NADH assay to follow the downstream 3-PG readout. Native RuBP provided the positive control. PRK/Ru5P and PHI/F6P conditions then tested routes that required a supporting enzyme, with inclusion and omission controls to help interpret the resulting traces.', '我建立了以 NADH 变化读取下游 3-PG 信号的酶偶联检测体系。先用天然底物 RuBP 获得阳性对照，再加入 PRK/Ru5P 和 PHI/F6P 条件，考察需要辅助酶参与的路线，并通过加入或省略辅助酶来辅助判断曲线来源。')}/>
 <SourceFigure src="/evidence/hubisco/coupled-assay.svg" title={t('How the coupled assay produces a readout','偶联检测如何产生读数')} caption={t('3-PG is coupled through PGK and GAPDH to NADH consumption. The native PRK/Ru5P route supplies RuBP; the PHI/F6P route supplies the exploratory Hu6P condition.', '3-PG 经 PGK 和 GAPDH 偶联到 NADH 消耗。天然底物路线由 PRK 将 Ru5P 转化为 RuBP；PHI/F6P 路线则为探索条件提供 Hu6P。')} notes={t('The Hu6P-to-3-PG arrow is the reaction being tested in this design. It does not indicate that Hu6P conversion was experimentally established.', '图中 Hu6P 指向 3-PG 的箭头表示这套设计希望检验的反应，不代表已通过实验确认 Hu6P 转化。')} source={t('Original Coupled Assay.svg; project dissertation assay design.', '来源：Coupled Assay.svg；项目论文检测体系设计章节。')}/>
 <SourceFigure src="/evidence/hubisco/native-assay.webp" crop={{width:1600,height:1134,box:[62,62,1518,1066]}} title={t('WT RuBisCO: the assay benchmark','WT RuBisCO：建立检测基准')} caption={t('The retained WT figure shows a clear response in the RuBP condition alongside the precursor-route controls. Arrows mark substrate addition.', 'WT 原始实验图显示 RuBP 条件的明显响应，并列出前体路线的对照。箭头标出加入底物的时间。')} notes={t('The source figure contains reported rate estimates. They are reproduced rather than re-fitted here. A coupled readout depends on the supporting reactions and background, so exploratory signals require additional controls and product confirmation.', '图中的速率估计保留自原报告，本站未重新拟合。偶联读数受辅助反应和背景影响，探索条件的微弱信号仍需额外对照和产物确认。')} source={t('Original WT Assay.svg; dissertation, WT assays on Ru5P and F6P.', '来源：WT Assay.svg；项目论文中的 WT、Ru5P 和 F6P 实验章节。')}/></section>
 <section className="editorial-section" id="phi"><Chapter number="04" title={t('Express PHI and verify precursor conversion by NMR.', '表达 PHI，并用 NMR 检验前体转化。')} body={t('I prepared PHI and developed an NMR-based check of the precursor reaction. The phosphorus-31 spectra supported the formation of a Hu6P-assigned product from F6P. This established a working part of the substrate-supply route and showed that precursor availability changed substantially with incubation time.', '我制备了 PHI，并建立了用 NMR 检验前体反应的方法。磷-31 谱支持 F6P 反应体系中出现归属于 Hu6P 的产物。这验证了底物供给路线中的一个环节，也说明前体供给会随孵育时间明显变化。')}/>
 <SourceFigure src="/evidence/hubisco/nmr.webp" title={t('Phosphorus-31 NMR: 0, 24 and 144 hours','磷-31 NMR：0、24 与 144 小时')} caption={t('The source assigns the growing peak near 4.25 ppm to Hu6P and the main peak near 3.75 ppm to F6P. The reported Hu6P/F6P peak-area ratio rose from 0.035 at 24 hours to 0.196 at 144 hours.', '原记录将约 4.25 ppm 处逐渐升高的峰归属于 Hu6P，将约 3.75 ppm 处的主峰归属于 F6P。报告中的 Hu6P/F6P 峰面积比从 24 小时的 0.035 升至 144 小时的 0.196。')} notes={t('The experiment followed PHI-mediated chemistry at 298 K. These spectra characterise precursor conversion, not RuBisCO catalysis. The peak ratio is not presented as an independently verified absolute product concentration.', '实验在 298 K 下跟踪 PHI 催化的反应。该谱表征前体转化，不是 RuBisCO 催化活性的直接读数；峰面积比也未被当作经过独立验证的绝对产物浓度。')} source={t('Bill NMR 0–144 hrs.svg; dissertation, PHI activity characterisation. NMR support: Dr David Russell.', '来源：Bill NMR 0–144 hrs.svg；论文 PHI 活性表征章节。NMR 工作得到 David Russell 博士协助。')}/><NmrChart/></section>
 <section className="editorial-section" id="evidence"><Chapter number="05" title={t('Purify the mutants and confirm that they still catalyse the native reaction.', '制备突变体，确认它们仍能催化天然底物反应。')} body={t('WT RuBisCO, I164T, S368C, S368A and PHI were expressed and purified. All three RuBisCO variants showed measurable RuBP activity. That was an essential control: the alternative-substrate experiments were being run with catalytically active preparations, although native activity was lower than WT.', '我完成了 WT RuBisCO、I164T、S368C、S368A 和 PHI 的表达与纯化。三个 RuBisCO 突变体均显示可测的 RuBP 活性，尽管低于 WT。这一对照很关键：后续替代底物实验使用的是仍具催化活性的蛋白制备物。')}/>
 <SourceFigure src="/evidence/hubisco/purification.webp" crop={{width:708,height:1146,box:[18,44,680,1095]}} title={t('Expression and purified preparations','表达与纯化样品')} caption={t('Panel a follows the WT purification workflow; panel b shows WT, the three mutants and PHI. Original lane labels and molecular-weight markers are preserved.', 'a 面板记录 WT 纯化流程；b 面板展示 WT、三个突变体及 PHI。原始泳道标签和分子量标记均完整保留。')} notes={t('Less S368C sample was loaded, and the source notes residual bands in some preparations. Gel brightness is not a direct comparison of expression yield.', 'S368C 上样量较少，原记录也指出部分制备物存在杂带。不能直接用胶图亮度比较表达产量。')} source={t('Project dissertation, Figure 4a–b, page 11.', '来源：项目论文第 11 页，图 4a–b。')}/>
 <SourceFigure src="/evidence/hubisco/native-mutants.svg" crop={{width:2641,height:2948,box:[125,112,2425,2620]}} title={t('WT and mutant activity on native RuBP','WT 与突变体的天然 RuBP 活性')} caption={t('The original native-RuBP figure shows measurable responses from WT, I164T, S368C and S368A. The legend retains the dissertation’s reported activity estimates.', '天然 RuBP 实验原图显示 WT、I164T、S368C 和 S368A 均有可测响应，图例保留了论文报告的活性估计。')} notes={t('Different protein inputs were used in the native traces, so raw slopes should not be used to rank intrinsic activity. The activity estimates are reported values, not a new fit or independent kinetic validation.', '天然底物曲线使用的蛋白量不同，不能直接用斜率排列酶的本征活性。活性估计保留自原报告，本站未重新拟合或独立验证其动力学参数。')} source={t('Project dissertation, Figure 4 and the accompanying expression and native-activity discussion.', '来源：项目论文图 4，以及表达、纯化和天然底物活性的相关讨论。')}/>
 <h3><Copy>{t('Then test the exploratory substrates','再进入替代底物条件')}</Copy></h3><p><Copy>{t('The native control worked, but the mono-phosphate conditions did not give a clear alternative-substrate response. Some I164T and S368C traces contained weak signals that could not be separated from background without repeats. I therefore used the structural models to ask what the missing phosphate and the mutations were changing.', '天然底物阳性对照成立，但单磷酸底物条件没有给出明确的替代底物响应。I164T 和 S368C 的部分曲线出现微弱信号，缺少重复测量，无法与背景区分。我因此回到结构模型，进一步考察缺失的磷酸基团和这些突变究竟改变了什么。')}</Copy></p><MutantAssays/></section>
 <section className="editorial-section" id="docking"><Chapter number="06" title={t('Use docking to define the next design problem.', '用 docking 明确下一轮需要解决的设计问题。')} body={t('I first redocked RuBP to compare the predicted pose with the deposited ligand, then examined HuBP and Hu6P in WT and mutant models using AutoDock Vina. The useful insight was the position and orientation of the sugar phosphate: opening space alone could also weaken the anchoring needed to place the reactive group.', '我先将 RuBP 重新对接，与晶体结构中的配体位置比较，再用 AutoDock Vina 考察 HuBP 和 Hu6P 在 WT 及突变模型中的构象。关键线索来自糖磷酸的位置和方向：单纯腾出空间，也可能削弱让反应基团正确就位所需的锚定作用。')}/>
 <SourceFigure src="/evidence/hubisco/rubp-redocking.svg" crop={{width:1280,height:720,box:[32,0,1216,720]}} title={t('RuBP redocking as a qualitative reference','以 RuBP 重对接作为定性参照')} caption={t('The predicted RuBP pose is compared with the deposited ligand. Local discrepancies, including near O3, limit how confidently a new pose can be interpreted.', '将预测的 RuBP 构象与晶体结构中的配体叠合比较。O3 附近等局部位置仍有偏差，因此新底物构象的解释需要保留这一模型局限。')} notes={t('This is a qualitative pose check. A quantitative redocking validation such as an RMSD benchmark was not established in the retained record.', '这是定性的构象检查；保留记录中未建立基于 RMSD 等指标的定量重对接验证。')} source={t('Project dissertation, RuBP redocking reference figure.', '来源：项目论文中的 RuBP 重对接参考图。')}/><DockingRecords/>
 <div className="practice-grid">{[
 [t('Preserve phosphate anchoring','保留磷酸锚定'),t('HuBP retained more of the C1-phosphate anchoring than Hu6P. This makes access to verified HuBP a priority before judging whether the engineering idea works.', 'HuBP 比 Hu6P 保留了更多 C1 磷酸附近的锚定作用。因此，下一步应优先获得并确认 HuBP，再直接检验这条酶改造路线。')],
 [t('Design for orientation, not just room','同时设计空间与方向'),t('I164T suggested a possible new polar contact, while Hu6P could adopt a reversed pose. S368 substitutions loosened local contacts. Future variants should create space without losing productive substrate orientation.', 'I164T 提示了新的潜在极性接触，但 Hu6P 也可能反向结合；S368 替换则松动了局部接触。后续设计需要在增加空间的同时，保留有利于反应的底物方向。')],
 [t('Separate substrate supply from readout','分开处理底物供给与检测'),t('Pre-incubating and characterising the PHI reaction, then using matched enzyme inputs, repeats and an independent product assay would make a future activity result easier to attribute.', '先预孵育并表征 PHI 反应，再采用匹配的酶量、重复测量和独立产物检测，可以更清楚地判断后续活性信号来自哪一步。')]
 ].map(([title,body],i)=><article key={i}><h3><Copy>{title}</Copy></h3><p><Copy>{body}</Copy></p></article>)}</div></section>
 <section className="editorial-section editorial-grid" id="contribution"><div><p className="eyebrow"><Copy>{t('My contribution','我的工作')}</Copy></p><h2><Copy>{t('Building the system in a new lab.','参与新实验室的搭建与方法建立。')}</Copy></h2></div><div><p><Copy>{t('I joined Dr Noam Prywes as he was establishing his Cambridge lab and helped set up its experimental work through protein expression, purification and assay workflows. The project gave me responsibility across substrate preparation, protein biochemistry, measurement development and structural interpretation.', '在 Noam Prywes 博士刚开始组建剑桥实验室时，我参与了实验室的搭建，并通过蛋白表达、纯化和活性检测建立实验流程。这个项目让我从底物制备、蛋白生化和检测方法，一直做到结构分析与下一步实验设计。')}</Copy></p><p><Copy>{t('Dr Prywes supervised the research, and Dr David Russell supported the NMR work. I contributed to preparation and interpretation of the NMR experiments alongside the wider protein and assay work.', 'Prywes 博士指导了研究，David Russell 博士协助了 NMR 工作。除蛋白与活性检测实验外，我也参与了 NMR 实验的样品准备和结果分析。')}</Copy></p><SiteLink className="text-link" href="https://pryweslab.org/" target="_blank" rel="noreferrer"><Copy>{t('Visit the Prywes Lab ↗','访问 Prywes Lab 网站 ↗')}</Copy></SiteLink></div></section>
 <section id="sources" className="source-disclosure"><h3><Copy>{t('Project records','项目资料')}</Copy></h3><p><Copy>{t('The experimental account and figures follow the project dissertation and retained laboratory records. The docking table is transcribed from the Vina output files. The original brief remains available as a project overview; the detailed account above distinguishes measured results from modelling hypotheses.', '实验叙述与图件依据项目论文及保留的实验记录；对接表来自 Vina 输出文件。原项目简介仍可下载，作为项目概览；本页的详细叙述区分了实测结果和模型提出的假设。')}</Copy></p><div className="actions"><SiteLink className="button primary" href="/downloads/HuBisCO-project-brief.pdf" download><Copy>Download project brief (PDF) ↓</Copy></SiteLink><SiteLink className="text-link" href="/projects"><Copy>Other research ↗</Copy></SiteLink></div></section>
 </CaseShell>;
}
