import {build} from 'esbuild';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
// Exercise real SQL and HTTP handling. JWT cryptography is tested separately.
await build({entryPoints:['backend/worker.ts'],outfile:'qa/worker-test.mjs',bundle:true,platform:'node',format:'esm',loader:{'.html':'text'},plugins:[{name:'test-identity',setup(b){b.onResolve({filter:/^\.\/auth$/},()=>({path:'test-identity',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export async function verifyOwner(token){if(token!=="test-owner")throw Error("unauthorized");return "owner"}'}));}}]});
const worker=(await import('../qa/worker-test.mjs')).default;
const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync('backend/schema.sql','utf8'));
const q=JSON.parse(fs.readFileSync('public/question-bank/esat.json','utf8')).questions[0];
sqlite.prepare('INSERT INTO questions(bank,id,base) VALUES(?,?,?)').run('esat',q.id,JSON.stringify(q));
const DB={prepare(sql){let args=[];return{bind(...values){args=values;return this},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return{results:sqlite.prepare(sql).all(...args)}},async run(){return sqlite.prepare(sql).run(...args)}}}};
const origin='https://admin.example.test',env={DB,PUBLIC_ORIGIN:'https://betoadfish.github.io'};
const call=(path,body,owner=true,requestOrigin=origin)=>worker.fetch(new Request(origin+path,{method:body?'POST':'GET',headers:{...(owner?{'Cf-Access-Jwt-Assertion':'test-owner'}:{}),...(body?{'Content-Type':'application/json',Origin:requestOrigin}:{})},body:body?JSON.stringify(body):undefined}),env);
const path='/admin/api/esat/'+q.id;
assert.equal((await call('/admin',null,false)).status,401);
assert.equal((await call(path,{action:'unpublish',revision:1},false)).status,401);
assert.equal((await call(path,{action:'unpublish',revision:1},true,'https://other.test')).status,403);
assert.equal((await call(path,{action:'save',revision:1,patch:{summary:'Reviewed question'}})).status,200);
assert.deepEqual(await(await call('/public/esat',null,false)).json(),[]);
assert.equal((await call(path,{action:'publish',revision:1})).status,409);
assert.equal((await call(path,{action:'publish',revision:2})).status,200);
let publicResponse=await call('/public/esat',null,false);assert.equal(publicResponse.headers.get('Access-Control-Allow-Origin'),env.PUBLIC_ORIGIN);
assert.deepEqual(await publicResponse.json(),[{id:q.id,published:{summary:'Reviewed question'},revision:3}]);
assert.equal((await call(path,{action:'unpublish',revision:3})).status,200);
assert.equal((await(await call('/public/esat',null,false)).json())[0].published,null);
assert.equal((await call(path,{action:'save',revision:4,patch:{note:'private'}})).status,400);
assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM audit').get().n,3);
assert.equal((await call('/admin/api/backup',null,false)).status,401);
assert.equal((await(await call('/admin/api/backup')).json()).questions.length,1);
sqlite.close();console.log('Admin SQL: drafts stay private, publish/withdraw work, stale edits and unauthenticated writes rejected.');
