import { CaseShell } from '@/components/case-shell';
import { PetExplorer } from '@/components/pet-explorer';
export const metadata = {title: 'PET hydrolases | Bill Huang', description: 'Protein expression, purification and an interactive view of retained CCH11 assay records.'};
export default function PET(){return <CaseShell theme="pet" title="PET hydrolases" subtitle="Producing proteins for experimental characterisation." role="Research intern" date="June - July 2025 · Four weeks" institution="Centre for Enzyme Innovation, University of Portsmouth" summary="Before comparing catalytic performance, we needed enough soluble protein to purify and test. I worked on the expression and characterisation of PET hydrolases, including CCH11 and TurboPETase.">
 <section className="editorial-section"><p className="eyebrow">The practical problem</p><div className="editorial-grid"><h2>Where was the protein being lost?</h2><div><p>I worked on small-scale expression trials, comparing constructs, bacterial strains and IPTG induction conditions. SDS-PAGE helped assess the material obtained. Selected conditions went into larger cultures, followed by His-tag affinity purification and size-exclusion chromatography.</p><p>My summer report records improved recovery of CCH11, while TurboPETase remained difficult to recover because of suspected solubility problems.</p></div></div></section>
 <section className="editorial-section"><p className="eyebrow">Production decisions</p><h2>Examine each stage of the preparation.</h2><div className="decision-path">{[
 ['Expression','Compare constructs and induction conditions.','Low expression and poor solubility need different responses. Small-scale trials helped determine which material could be carried forward.'],
 ['Purification','Track recovery through affinity purification and SEC.','The amount recovered depends on both expression and losses during preparation. A weak activity signal alone cannot distinguish those causes.'],
 ['Host and tag','Reconsider the expression system.','My project account describes tag changes and a move from bacterial to yeast expression, followed by calorimetry. Folding and post-translational modification remained possible explanations, rather than isolated causes.'],
 ['Characterisation','Read the assay alongside the preparation history.','The retained plate-reader record below shows individual test and control wells. Matched protein loading and a calibrated product assay would be needed for a stronger performance comparison.']
 ].map(([t,s,b],i)=><details key={t} className="decision-step" open={i===0}><summary><span>0{i+1}</span><h3>{t}</h3><p>{s}</p></summary><p>{b}</p></details>)}</div></section>
 <PetExplorer/>
 <section className="editorial-section editorial-grid"><div><p className="eyebrow">My contribution</p><h2>Production and analysis.</h2></div><div><p>I carried out expression trials, worked on protein preparation and used laboratory readouts to assess the material. The project also involved plate-reader assays and HPLC-based characterisation. The narrative here follows my summer report and personal project account; the interactive traces come from a retained project workbook.</p><p>Changing the host affected several properties at once. I would now compare preparations with matched enzyme loading, documented preparation histories and calibrated product measurements before assigning a cause to a performance difference.</p></div></section>
 <details className="source-disclosure"><summary>Sources and scope</summary><p>Summer Bursaries Report, section A; personal research account; retained instrument-export workbook dated 26 June 2025, CCH11 and Sheet3. The report supports the work described here. It does not independently validate a mechanism for improved protein recovery.</p></details>
 </CaseShell>;}
